/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { aiservicesPromptExecutePrompt } from "../funcs/aiservicesPromptExecutePrompt.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AiservicesPrompt extends ClientSDK {
  /**
   * Execute a predefined prompt
   *
   * @remarks
   * Execute a published and active prompt template from the AI console.
   */
  async executePrompt(
    request: operations.ExecutePromptRequest,
    options?: RequestOptions,
  ): Promise<models.ExecutePromptResponse> {
    return unwrapAsync(aiservicesPromptExecutePrompt(
      this,
      request,
      options,
    ));
  }
}
