/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Answers } from "./answers.js";
import { Retrieve } from "./retrieve.js";

export class Aiservices extends ClientSDK {
  private _retrieve?: Retrieve;
  get retrieve(): Retrieve {
    return (this._retrieve ??= new Retrieve(this._options));
  }

  private _answers?: Answers;
  get answers(): Answers {
    return (this._answers ??= new Answers(this._options));
  }
}
