/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { portalFederatedsearcheventCreateFederatedSearchResultEvent } from "../funcs/portalFederatedsearcheventCreateFederatedSearchResultEvent.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Federatedsearchevent extends ClientSDK {
  /**
   * Event For Viewed Federated Search Result
   *
   * @remarks
   * ## Overview
   *    The Federated Search Event API creates an event for federated search results that have been viewed.
   *   An event for viewing an:
   *   * External web page cannot be created for a portal where the value for the "Include Web Search Section in Search Results" attribute is "Yes".
   *   * Internal web page cannot be created for a portal where the value for the "Include Intranet Search Section in Search Results" attribute is "Yes".
   */
  async createFederatedSearchResultEvent(
    request: operations.CreateFederatedSearchResultEventRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      portalFederatedsearcheventCreateFederatedSearchResultEvent(
        this,
        request,
        options,
      ),
    );
  }
}
