/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { contentImportCancelImport } from "../funcs/contentImportCancelImport.js";
import { contentImportCreateImportJob } from "../funcs/contentImportCreateImportJob.js";
import { contentImportCreateImportValidationJob } from "../funcs/contentImportCreateImportValidationJob.js";
import { contentImportGetImportStatus } from "../funcs/contentImportGetImportStatus.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Import extends ClientSDK {
  /**
   * Create Import Job
   *
   * @remarks
   * # Import Content
   *
   * ## Overview
   * This API initiates a bulk content import operation from Data Sources. It creates an asynchronous import job that processes content in the background, allowing you to import large volumes of content without blocking your application.
   *
   * ## Pre-requisties
   * 1. Content in Data Source needs to be in this format: [Guide to Data Import Format](https://apidev.egain.com/developer-portal/guides/ingestion/data-import-format-guide/)
   *
   * ## How It Works
   * 1. **Job Creation**: The API creates an import job and returns a unique job ID
   * 2. **Content Processing**: Content is processed asynchronously in the background
   * 3. **Status Monitoring**: Use the job ID to monitor progress via the Status API
   * 4. **Completion**: Job completes when all content is processed or errors occur
   *
   * **Note:** After a successful import, please allow for a brief delay before the content is fully available for use. The system's search service synchronizes all new and updated content every 30 minutes.
   *
   * ## Supported Operations
   * - **Import**: Add new content to the knowledge base
   * - **Update**: Modify existing content
   *
   * ## Data Source Types
   * - AWS S3 bucket
   * - Shared file path
   *
   * ## Best Practices
   * - **Scheduling**: Use scheduleTime for off-peak imports to minimize system impact.  Please note that jobs can only be scheduled for a maximum of 7 days from the current date and time.
   * - **Monitoring**: Regularly check job status and logs for any issues
   * - **Error Handling**: Review failed items and retry with corrections
   */
  async createImportJob(
    request: models.ImportContent,
    options?: RequestOptions,
  ): Promise<operations.CreateImportJobResponse | undefined> {
    return unwrapAsync(contentImportCreateImportJob(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Job Status
   *
   * @remarks
   * # Get Import Job Status
   *
   * ## Overview
   * This API provides real-time status information for content import and validation operations. Use this endpoint to monitor job progress, check completion status, and access detailed logs and error information.
   *
   * ## Status Values
   * - **Scheduled**: Job is queued and waiting for scheduled execution time
   * - **In Progress**: Job is actively processing content
   * - **Completed**: Job finished successfully
   * - **Failed**: Job encountered errors and could not complete
   * - **Cancelled**: Job was manually cancelled by user
   *
   * ## Response Information
   * - **Current Status**: Real-time job status
   * - **Progress Metrics**: Items processed, total items, completion percentage
   * - **Log Files**: Location of detailed operation logs
   * - **Error Details**: Specific errors encountered during processing
   * - **Timing Information**: Start time, estimated completion, actual completion
   *
   * ## Log File Access
   * Log files contain detailed information about:
   * - Content processing steps
   * - Validation results
   * - Error details with context
   */
  async getImportStatus(
    request: operations.GetImportStatusRequest,
    options?: RequestOptions,
  ): Promise<models.ImportStatus> {
    return unwrapAsync(contentImportGetImportStatus(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Validation Job
   *
   * @remarks
   * # Validate Import Content
   *
   * ## Overview
   * This API enables users to validate content structure, format, and compliance before importing it into the production knowledge base. Validation is a non-destructive operation that checks content without making any changes to your existing data.
   *
   * ## What Validation Checks
   * - **Content Structure**: Verifies required fields and data types
   * - **Format Compliance**: Ensures content meets platform requirements
   * - **Language Support**: Validates content against supported languages
   * - **Metadata Mapping**: Checks field mappings and transformations
   * - **Business Rules**: Validates against department-specific rules
   *
   * ## Validation Benefits
   * - **Risk Mitigation**: Identify issues before affecting production data
   * - **Quality Assurance**: Ensure content meets organizational standards
   * - **Cost Savings**: Avoid failed imports that waste processing time
   * - **Compliance**: Meet regulatory and internal content requirements
   *
   * ## Validation Process
   * 1. **Content Analysis**: System analyzes content structure and format
   * 2. **Rule Validation**: Applies business rules and validation logic
   * 3. **Quality Assessment**: Evaluates content quality and completeness
   * 4. **Report Generation**: Creates detailed validation report
   * 5. **Issue Categorization**: Classifies issues by severity and type
   *
   * ## Common Validation Issues
   * - **Missing Required Fields**: Title, description, category, etc.
   * - **Invalid Data Types**: Incorrect field formats (dates, numbers, etc.)
   * - **Language Mismatches**: Content language not supported by department
   *
   * ## Best Practices
   * - **Always Validate First**: Run validation before any import operation
   * - **Review Reports**: Carefully examine validation results and warnings
   * - **Fix Issues**: Address validation errors before proceeding with import
   * - **Test Small Batches**: Validate with small content samples first
   * - **Iterate**: Use validation feedback to improve content quality
   */
  async createImportValidationJob(
    request: models.ValidateImportContent,
    options?: RequestOptions,
  ): Promise<operations.CreateImportValidationJobResponse | undefined> {
    return unwrapAsync(contentImportCreateImportValidationJob(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel Job
   *
   * @remarks
   * # Cancel Import or Validation Job
   *
   * ## Overview
   * This API allows users to cancel import or validation operations that are currently in progress or scheduled for future execution. Cancellation is immediate for scheduled jobs and graceful for running jobs.
   *
   * ## Cancellation Behavior
   * - **Scheduled Jobs**: Immediate cancellation, no processing occurs
   * - **In Progress Jobs**: Graceful shutdown, current item completes, no new items start
   * - **Completed Jobs**: Cannot be cancelled (returns error)
   * - **Failed Jobs**: Cannot be cancelled (already stopped)
   *
   * ## When to Cancel
   * - **Content Issues**: Discover problems with source content
   * - **Timing Changes**: Need to reschedule for different time
   * - **Resource Constraints**: System resources are needed elsewhere
   * - **User Request**: Manual cancellation by authorized users
   * - **System Maintenance**: Planned maintenance windows
   *
   * ## Cancellation Process
   * 1. **Request Received**: System receives cancellation request
   * 2. **Status Check**: Verifies current job status
   * 3. **Graceful Shutdown**: For running jobs, completes current item
   * 4. **Resource Cleanup**: Releases allocated system resources
   * 5. **Status Update**: Marks job as cancelled
   * 6. **Notification**: Updates job status and logs
   *
   * ## Post-Cancellation
   * - **Job Status**: Changes to "Cancelled"
   * - **Partial Results**: Any completed items remain in system
   * - **Logs**: Cancellation reason and timing recorded
   * - **Resources**: System resources freed for other operations
   *
   * ## Best Practices
   * - **Monitor Jobs**: Regularly check job status to identify candidates for cancellation
   * - **Plan Cancellations**: Schedule cancellations during low-usage periods
   * - **Resource Planning**: Consider resource impact before cancelling large jobs
   */
  async cancelImport(
    request: operations.CancelImportRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(contentImportCancelImport(
      this,
      request,
      options,
    ));
  }
}
