/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { promptGetPromptTemplateById } from "../funcs/promptGetPromptTemplateById.js";
import { promptGetPromptTemplates } from "../funcs/promptGetPromptTemplates.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Prompt extends ClientSDK {
  /**
   * Get Prompt Templates
   *
   * @remarks
   * Retrieve prompt templates filtered by department and language.
   */
  async getPromptTemplates(
    request: operations.GetPromptTemplatesRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPromptTemplatesResponse | undefined> {
    return unwrapAsync(promptGetPromptTemplates(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Prompt Template By ID
   *
   * @remarks
   * Retrieve a prompt template filtered by department and language.
   */
  async getPromptTemplateById(
    request: operations.GetPromptTemplateByIdRequest,
    options?: RequestOptions,
  ): Promise<models.PromptTemplate | undefined> {
    return unwrapAsync(promptGetPromptTemplateById(
      this,
      request,
      options,
    ));
  }
}
