/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { portalUserdetailsGetUserDetails } from "../funcs/portalUserdetailsGetUserDetails.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Userdetails extends ClientSDK {
  /**
   * Get User Details
   *
   * @remarks
   * ## Overview
   *   The Get User Details API retrieves details of a knowledge user.
   */
  async getUserDetails(
    request: operations.GetUserDetailsRequest,
    options?: RequestOptions,
  ): Promise<models.UserDetails | undefined> {
    return unwrapAsync(portalUserdetailsGetUserDetails(
      this,
      request,
      options,
    ));
  }
}
