/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { portalUsermilestonesGetUserMilestones } from "../funcs/portalUsermilestonesGetUserMilestones.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Usermilestones extends ClientSDK {
  /**
   * Get User Milestones
   *
   * @remarks
   * ## Overview
   * The User Milestones API provides information about the milestones of an agent within the article workflow.
   * This API helps track the progress of articles by grouping them into relevant milestones based on their current stage.
   *
   * For example, an article might go through Knowledge Workflow Stages like Draft, Initial Review, Staging, Final Review and Publish.
   *        Articles in the Draft and Initial Review stages are part of the "authoring milestone", while articles in the Staging and Final Review stages are part of the "staging milestone".
   */
  async getUserMilestones(
    request: operations.GetUserMilestonesRequest,
    options?: RequestOptions,
  ): Promise<models.Milestones | undefined> {
    return unwrapAsync(portalUsermilestonesGetUserMilestones(
      this,
      request,
      options,
    ));
  }
}
