/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AddAsReferenceRequest = {
  /**
   * The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses).
   */
  acceptLanguage: models.AcceptLanguage;
  /**
   * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  portalID: string;
  /**
   * The ID of the Article.<br><br>An Article ID is composed of a 2-4 letter prefix followed by a dash and 4-15 digits.
   */
  articleID: string;
  articleActivityLink: models.ArticleActivityLink;
};

/** @internal */
export const AddAsReferenceRequest$inboundSchema: z.ZodType<
  AddAsReferenceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "Accept-Language": models.AcceptLanguage$inboundSchema,
  portalID: z.string(),
  articleID: z.string(),
  ArticleActivityLink: models.ArticleActivityLink$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Accept-Language": "acceptLanguage",
    "ArticleActivityLink": "articleActivityLink",
  });
});

/** @internal */
export type AddAsReferenceRequest$Outbound = {
  "Accept-Language": string;
  portalID: string;
  articleID: string;
  ArticleActivityLink: models.ArticleActivityLink$Outbound;
};

/** @internal */
export const AddAsReferenceRequest$outboundSchema: z.ZodType<
  AddAsReferenceRequest$Outbound,
  z.ZodTypeDef,
  AddAsReferenceRequest
> = z.object({
  acceptLanguage: models.AcceptLanguage$outboundSchema,
  portalID: z.string(),
  articleID: z.string(),
  articleActivityLink: models.ArticleActivityLink$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    acceptLanguage: "Accept-Language",
    articleActivityLink: "ArticleActivityLink",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddAsReferenceRequest$ {
  /** @deprecated use `AddAsReferenceRequest$inboundSchema` instead. */
  export const inboundSchema = AddAsReferenceRequest$inboundSchema;
  /** @deprecated use `AddAsReferenceRequest$outboundSchema` instead. */
  export const outboundSchema = AddAsReferenceRequest$outboundSchema;
  /** @deprecated use `AddAsReferenceRequest$Outbound` instead. */
  export type Outbound = AddAsReferenceRequest$Outbound;
}

export function addAsReferenceRequestToJSON(
  addAsReferenceRequest: AddAsReferenceRequest,
): string {
  return JSON.stringify(
    AddAsReferenceRequest$outboundSchema.parse(addAsReferenceRequest),
  );
}

export function addAsReferenceRequestFromJSON(
  jsonString: string,
): SafeParseResult<AddAsReferenceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddAsReferenceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddAsReferenceRequest' from JSON`,
  );
}
