/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AddbookmarkRequest = {
  /**
   * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  portalID: string;
  /**
   * The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses).
   */
  acceptLanguage: models.AcceptLanguage;
  createBookmark: models.CreateBookmark;
};

/** @internal */
export const AddbookmarkRequest$inboundSchema: z.ZodType<
  AddbookmarkRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  portalID: z.string(),
  "Accept-Language": models.AcceptLanguage$inboundSchema,
  CreateBookmark: models.CreateBookmark$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Accept-Language": "acceptLanguage",
    "CreateBookmark": "createBookmark",
  });
});

/** @internal */
export type AddbookmarkRequest$Outbound = {
  portalID: string;
  "Accept-Language": string;
  CreateBookmark: models.CreateBookmark$Outbound;
};

/** @internal */
export const AddbookmarkRequest$outboundSchema: z.ZodType<
  AddbookmarkRequest$Outbound,
  z.ZodTypeDef,
  AddbookmarkRequest
> = z.object({
  portalID: z.string(),
  acceptLanguage: models.AcceptLanguage$outboundSchema,
  createBookmark: models.CreateBookmark$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    acceptLanguage: "Accept-Language",
    createBookmark: "CreateBookmark",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddbookmarkRequest$ {
  /** @deprecated use `AddbookmarkRequest$inboundSchema` instead. */
  export const inboundSchema = AddbookmarkRequest$inboundSchema;
  /** @deprecated use `AddbookmarkRequest$outboundSchema` instead. */
  export const outboundSchema = AddbookmarkRequest$outboundSchema;
  /** @deprecated use `AddbookmarkRequest$Outbound` instead. */
  export type Outbound = AddbookmarkRequest$Outbound;
}

export function addbookmarkRequestToJSON(
  addbookmarkRequest: AddbookmarkRequest,
): string {
  return JSON.stringify(
    AddbookmarkRequest$outboundSchema.parse(addbookmarkRequest),
  );
}

export function addbookmarkRequestFromJSON(
  jsonString: string,
): SafeParseResult<AddbookmarkRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddbookmarkRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddbookmarkRequest' from JSON`,
  );
}
