/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AddSuggestionCommentRequest = {
  /**
   * The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses).
   */
  acceptLanguage: models.AcceptLanguage;
  /**
   * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  portalID: string;
  /**
   * The ID of the Suggestion.<br><br>A Suggestion ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  suggestionID: string;
  createComment: models.CreateComment;
};

/** @internal */
export const AddSuggestionCommentRequest$inboundSchema: z.ZodType<
  AddSuggestionCommentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "Accept-Language": models.AcceptLanguage$inboundSchema,
  portalID: z.string(),
  suggestionID: z.string(),
  CreateComment: models.CreateComment$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Accept-Language": "acceptLanguage",
    "CreateComment": "createComment",
  });
});

/** @internal */
export type AddSuggestionCommentRequest$Outbound = {
  "Accept-Language": string;
  portalID: string;
  suggestionID: string;
  CreateComment: models.CreateComment$Outbound;
};

/** @internal */
export const AddSuggestionCommentRequest$outboundSchema: z.ZodType<
  AddSuggestionCommentRequest$Outbound,
  z.ZodTypeDef,
  AddSuggestionCommentRequest
> = z.object({
  acceptLanguage: models.AcceptLanguage$outboundSchema,
  portalID: z.string(),
  suggestionID: z.string(),
  createComment: models.CreateComment$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    acceptLanguage: "Accept-Language",
    createComment: "CreateComment",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddSuggestionCommentRequest$ {
  /** @deprecated use `AddSuggestionCommentRequest$inboundSchema` instead. */
  export const inboundSchema = AddSuggestionCommentRequest$inboundSchema;
  /** @deprecated use `AddSuggestionCommentRequest$outboundSchema` instead. */
  export const outboundSchema = AddSuggestionCommentRequest$outboundSchema;
  /** @deprecated use `AddSuggestionCommentRequest$Outbound` instead. */
  export type Outbound = AddSuggestionCommentRequest$Outbound;
}

export function addSuggestionCommentRequestToJSON(
  addSuggestionCommentRequest: AddSuggestionCommentRequest,
): string {
  return JSON.stringify(
    AddSuggestionCommentRequest$outboundSchema.parse(
      addSuggestionCommentRequest,
    ),
  );
}

export function addSuggestionCommentRequestFromJSON(
  jsonString: string,
): SafeParseResult<AddSuggestionCommentRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddSuggestionCommentRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddSuggestionCommentRequest' from JSON`,
  );
}
