/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ComplyArticleRequest = {
  /**
   * The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses).
   */
  acceptLanguage: models.AcceptLanguage;
  /**
   * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  portalID: string;
  /**
   * The ID of the Article.<br><br>An Article ID is composed of a 2-4 letter prefix followed by a dash and 4-15 digits.
   */
  articleID: string;
};

/** @internal */
export const ComplyArticleRequest$inboundSchema: z.ZodType<
  ComplyArticleRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "Accept-Language": models.AcceptLanguage$inboundSchema,
  portalID: z.string(),
  articleID: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Accept-Language": "acceptLanguage",
  });
});

/** @internal */
export type ComplyArticleRequest$Outbound = {
  "Accept-Language": string;
  portalID: string;
  articleID: string;
};

/** @internal */
export const ComplyArticleRequest$outboundSchema: z.ZodType<
  ComplyArticleRequest$Outbound,
  z.ZodTypeDef,
  ComplyArticleRequest
> = z.object({
  acceptLanguage: models.AcceptLanguage$outboundSchema,
  portalID: z.string(),
  articleID: z.string(),
}).transform((v) => {
  return remap$(v, {
    acceptLanguage: "Accept-Language",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ComplyArticleRequest$ {
  /** @deprecated use `ComplyArticleRequest$inboundSchema` instead. */
  export const inboundSchema = ComplyArticleRequest$inboundSchema;
  /** @deprecated use `ComplyArticleRequest$outboundSchema` instead. */
  export const outboundSchema = ComplyArticleRequest$outboundSchema;
  /** @deprecated use `ComplyArticleRequest$Outbound` instead. */
  export type Outbound = ComplyArticleRequest$Outbound;
}

export function complyArticleRequestToJSON(
  complyArticleRequest: ComplyArticleRequest,
): string {
  return JSON.stringify(
    ComplyArticleRequest$outboundSchema.parse(complyArticleRequest),
  );
}

export function complyArticleRequestFromJSON(
  jsonString: string,
): SafeParseResult<ComplyArticleRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ComplyArticleRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ComplyArticleRequest' from JSON`,
  );
}
