/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const CreateValidationHookVersionServerList = [
  /**
   * Production Server
   */
  "https://api.aidev.egain.cloud//knowledge/contentmgr/v4",
] as const;

export type CreateValidationHookVersionRequest = {
  /**
   * Integer ID of the Hook resource.
   */
  hookID: number;
  fileObject: models.FileObject;
};

/** @internal */
export const CreateValidationHookVersionRequest$inboundSchema: z.ZodType<
  CreateValidationHookVersionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  hookID: z.number().int(),
  FileObject: models.FileObject$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "FileObject": "fileObject",
  });
});

/** @internal */
export type CreateValidationHookVersionRequest$Outbound = {
  hookID: number;
  FileObject: models.FileObject$Outbound;
};

/** @internal */
export const CreateValidationHookVersionRequest$outboundSchema: z.ZodType<
  CreateValidationHookVersionRequest$Outbound,
  z.ZodTypeDef,
  CreateValidationHookVersionRequest
> = z.object({
  hookID: z.number().int(),
  fileObject: models.FileObject$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    fileObject: "FileObject",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateValidationHookVersionRequest$ {
  /** @deprecated use `CreateValidationHookVersionRequest$inboundSchema` instead. */
  export const inboundSchema = CreateValidationHookVersionRequest$inboundSchema;
  /** @deprecated use `CreateValidationHookVersionRequest$outboundSchema` instead. */
  export const outboundSchema =
    CreateValidationHookVersionRequest$outboundSchema;
  /** @deprecated use `CreateValidationHookVersionRequest$Outbound` instead. */
  export type Outbound = CreateValidationHookVersionRequest$Outbound;
}

export function createValidationHookVersionRequestToJSON(
  createValidationHookVersionRequest: CreateValidationHookVersionRequest,
): string {
  return JSON.stringify(
    CreateValidationHookVersionRequest$outboundSchema.parse(
      createValidationHookVersionRequest,
    ),
  );
}

export function createValidationHookVersionRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateValidationHookVersionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateValidationHookVersionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateValidationHookVersionRequest' from JSON`,
  );
}
