/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CreateSearchResultEventForConnectorsRequest = {
  /**
   * The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses).
   */
  acceptLanguage: models.AcceptLanguage;
  /**
   * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  portalID: string;
  createSearchResultEventForConnectors:
    models.CreateSearchResultEventForConnectors;
};

/** @internal */
export const CreateSearchResultEventForConnectorsRequest$inboundSchema:
  z.ZodType<
    CreateSearchResultEventForConnectorsRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    "Accept-Language": models.AcceptLanguage$inboundSchema,
    portalID: z.string(),
    createSearchResultEventForConnectors: z.lazy(() =>
      models.CreateSearchResultEventForConnectors$inboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      "Accept-Language": "acceptLanguage",
    });
  });

/** @internal */
export type CreateSearchResultEventForConnectorsRequest$Outbound = {
  "Accept-Language": string;
  portalID: string;
  createSearchResultEventForConnectors:
    models.CreateSearchResultEventForConnectors$Outbound;
};

/** @internal */
export const CreateSearchResultEventForConnectorsRequest$outboundSchema:
  z.ZodType<
    CreateSearchResultEventForConnectorsRequest$Outbound,
    z.ZodTypeDef,
    CreateSearchResultEventForConnectorsRequest
  > = z.object({
    acceptLanguage: models.AcceptLanguage$outboundSchema,
    portalID: z.string(),
    createSearchResultEventForConnectors: z.lazy(() =>
      models.CreateSearchResultEventForConnectors$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      acceptLanguage: "Accept-Language",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateSearchResultEventForConnectorsRequest$ {
  /** @deprecated use `CreateSearchResultEventForConnectorsRequest$inboundSchema` instead. */
  export const inboundSchema =
    CreateSearchResultEventForConnectorsRequest$inboundSchema;
  /** @deprecated use `CreateSearchResultEventForConnectorsRequest$outboundSchema` instead. */
  export const outboundSchema =
    CreateSearchResultEventForConnectorsRequest$outboundSchema;
  /** @deprecated use `CreateSearchResultEventForConnectorsRequest$Outbound` instead. */
  export type Outbound = CreateSearchResultEventForConnectorsRequest$Outbound;
}

export function createSearchResultEventForConnectorsRequestToJSON(
  createSearchResultEventForConnectorsRequest:
    CreateSearchResultEventForConnectorsRequest,
): string {
  return JSON.stringify(
    CreateSearchResultEventForConnectorsRequest$outboundSchema.parse(
      createSearchResultEventForConnectorsRequest,
    ),
  );
}

export function createSearchResultEventForConnectorsRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  CreateSearchResultEventForConnectorsRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreateSearchResultEventForConnectorsRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreateSearchResultEventForConnectorsRequest' from JSON`,
  );
}
