/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const CreateImportValidationJobServerList = [
  /**
   * Production Server - Try it Out does not function
   */
  "http://nop",
] as const;

export type CreateImportValidationJobResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export const CreateImportValidationJobResponse$inboundSchema: z.ZodType<
  CreateImportValidationJobResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});

/** @internal */
export type CreateImportValidationJobResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
};

/** @internal */
export const CreateImportValidationJobResponse$outboundSchema: z.ZodType<
  CreateImportValidationJobResponse$Outbound,
  z.ZodTypeDef,
  CreateImportValidationJobResponse
> = z.object({
  headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateImportValidationJobResponse$ {
  /** @deprecated use `CreateImportValidationJobResponse$inboundSchema` instead. */
  export const inboundSchema = CreateImportValidationJobResponse$inboundSchema;
  /** @deprecated use `CreateImportValidationJobResponse$outboundSchema` instead. */
  export const outboundSchema =
    CreateImportValidationJobResponse$outboundSchema;
  /** @deprecated use `CreateImportValidationJobResponse$Outbound` instead. */
  export type Outbound = CreateImportValidationJobResponse$Outbound;
}

export function createImportValidationJobResponseToJSON(
  createImportValidationJobResponse: CreateImportValidationJobResponse,
): string {
  return JSON.stringify(
    CreateImportValidationJobResponse$outboundSchema.parse(
      createImportValidationJobResponse,
    ),
  );
}

export function createImportValidationJobResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateImportValidationJobResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateImportValidationJobResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateImportValidationJobResponse' from JSON`,
  );
}
