/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeletebookmarkRequest = {
  /**
   * The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses).
   */
  acceptLanguage: models.AcceptLanguage;
  /**
   * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  portalID: string;
  /**
   * The ID of the bookmark.
   */
  bookmarkID: string;
};

/** @internal */
export const DeletebookmarkRequest$inboundSchema: z.ZodType<
  DeletebookmarkRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "Accept-Language": models.AcceptLanguage$inboundSchema,
  portalID: z.string(),
  bookmarkID: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Accept-Language": "acceptLanguage",
  });
});

/** @internal */
export type DeletebookmarkRequest$Outbound = {
  "Accept-Language": string;
  portalID: string;
  bookmarkID: string;
};

/** @internal */
export const DeletebookmarkRequest$outboundSchema: z.ZodType<
  DeletebookmarkRequest$Outbound,
  z.ZodTypeDef,
  DeletebookmarkRequest
> = z.object({
  acceptLanguage: models.AcceptLanguage$outboundSchema,
  portalID: z.string(),
  bookmarkID: z.string(),
}).transform((v) => {
  return remap$(v, {
    acceptLanguage: "Accept-Language",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeletebookmarkRequest$ {
  /** @deprecated use `DeletebookmarkRequest$inboundSchema` instead. */
  export const inboundSchema = DeletebookmarkRequest$inboundSchema;
  /** @deprecated use `DeletebookmarkRequest$outboundSchema` instead. */
  export const outboundSchema = DeletebookmarkRequest$outboundSchema;
  /** @deprecated use `DeletebookmarkRequest$Outbound` instead. */
  export type Outbound = DeletebookmarkRequest$Outbound;
}

export function deletebookmarkRequestToJSON(
  deletebookmarkRequest: DeletebookmarkRequest,
): string {
  return JSON.stringify(
    DeletebookmarkRequest$outboundSchema.parse(deletebookmarkRequest),
  );
}

export function deletebookmarkRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeletebookmarkRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeletebookmarkRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeletebookmarkRequest' from JSON`,
  );
}
