/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ExportStatusRequest = {
  /**
   * The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses).
   */
  acceptLanguage: models.AcceptLanguage;
  /**
   * **Example Usage:**
   *
   * @remarks
   * ```bash
   * GET /content/export/7A84B875-6F75-4C7B-B137-0632B62DB0BD/status
   * ```
   */
  jobID: string;
};

/** @internal */
export const ExportStatusRequest$inboundSchema: z.ZodType<
  ExportStatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "Accept-Language": models.AcceptLanguage$inboundSchema,
  jobID: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Accept-Language": "acceptLanguage",
  });
});

/** @internal */
export type ExportStatusRequest$Outbound = {
  "Accept-Language": string;
  jobID: string;
};

/** @internal */
export const ExportStatusRequest$outboundSchema: z.ZodType<
  ExportStatusRequest$Outbound,
  z.ZodTypeDef,
  ExportStatusRequest
> = z.object({
  acceptLanguage: models.AcceptLanguage$outboundSchema,
  jobID: z.string(),
}).transform((v) => {
  return remap$(v, {
    acceptLanguage: "Accept-Language",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExportStatusRequest$ {
  /** @deprecated use `ExportStatusRequest$inboundSchema` instead. */
  export const inboundSchema = ExportStatusRequest$inboundSchema;
  /** @deprecated use `ExportStatusRequest$outboundSchema` instead. */
  export const outboundSchema = ExportStatusRequest$outboundSchema;
  /** @deprecated use `ExportStatusRequest$Outbound` instead. */
  export type Outbound = ExportStatusRequest$Outbound;
}

export function exportStatusRequestToJSON(
  exportStatusRequest: ExportStatusRequest,
): string {
  return JSON.stringify(
    ExportStatusRequest$outboundSchema.parse(exportStatusRequest),
  );
}

export function exportStatusRequestFromJSON(
  jsonString: string,
): SafeParseResult<ExportStatusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExportStatusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExportStatusRequest' from JSON`,
  );
}
