/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetArticlesInTopicRequest = {
  /**
   * The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses).
   */
  acceptLanguage: models.AcceptLanguage;
  /**
   * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  portalID: string;
  /**
   * Search Profile ID
   */
  searchProfileId?: string | undefined;
  /**
   * The ID of the topic. It is used to restrict to a specific topic.
   */
  filterTopicId: string;
  /**
   * The attributes of an Article to be returned *in addition to* the default list of attributes, listed below. Multiple additional attributes can be specified using a comma-separated list. Passing 'all' will return all attributes.
   *
   * @remarks
   *
   * #### Default Attributes
   * These Article attributes are always returned:
   *
   * | Name | Description
   * | ---- | -----------
   * | id | The ID of the Article.
   * | name  | The name of the Article.
   * | articleType | The Article Type and its attributes.
   * | createdBy | The ID, first name, middle name and last name of the user that created the Article.
   * | createdDate | The date that the Article was created.
   * | hasAttachments | True: The Article has one or more attachments.<br>False: The Article does not have any attachments.
   * | languageCode | The language code of the Article language.
   * | modifiedBy | The ID, first name, middle name and last name of the user that last modified the Article.
   * | modifiedDate | The date that the Article was last modified on.
   * | link | The link object, used to retrieve the details of the Article.
   * | versionId | The ID of the Article version that is returned.
   */
  articleResultAdditionalAttributes?:
    | Array<models.ArticleResultAdditionalAttributes>
    | undefined;
  /**
   * A comma separated list of Tag / Tag Group IDs. The query results will be filtered by the tags that are specified.<br><br>Tag IDs and Tag Group IDs can be mixed together.
   */
  filterTags?: string | undefined;
  /**
   * For agents with the View Author Portal or View Staging Portal actions, this determines which version of the Article is returned.<li>'Authoring' returns the most recent version of an Article checked-in by an author.</li><li>'Staging' returns the updated version currently being processed in a workflow.</li><li>'Publish' returns the most recently published version.</li>
   */
  workflowMilestone?: models.WorkflowMilestone | undefined;
  /**
   * The language that describes the details of a resource. Resources available in different languages may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default language is used.</li>
   */
  language?: models.LanguageQueryParameter | undefined;
  /**
   * Pagination parameter that specifies the page number of results to be returned. Used in conjunction with $pagesize.
   */
  pagenum?: number | undefined;
  /**
   * Pagination parameter that specifies the number of results per page. Used in conjunction with $pagenum.
   */
  pagesize?: number | undefined;
  /**
   * Articles to be sorted on.
   */
  sort?: models.ArticleSort | undefined;
  /**
   * Sort order of articles.
   */
  order?: models.ArticleSortOrder | undefined;
};

/** @internal */
export const GetArticlesInTopicRequest$inboundSchema: z.ZodType<
  GetArticlesInTopicRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "Accept-Language": models.AcceptLanguage$inboundSchema,
  portalID: z.string(),
  searchProfileId: z.string().optional(),
  filterTopicId: z.string(),
  articleResultAdditionalAttributes: z.array(
    models.ArticleResultAdditionalAttributes$inboundSchema,
  ).optional(),
  filterTags: z.string().optional(),
  workflowMilestone: models.WorkflowMilestone$inboundSchema.optional(),
  language: models.LanguageQueryParameter$inboundSchema.optional(),
  pagenum: z.number().int().default(1),
  pagesize: z.number().int().default(10),
  sort: models.ArticleSort$inboundSchema.optional(),
  order: models.ArticleSortOrder$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "Accept-Language": "acceptLanguage",
  });
});

/** @internal */
export type GetArticlesInTopicRequest$Outbound = {
  "Accept-Language": string;
  portalID: string;
  searchProfileId?: string | undefined;
  filterTopicId: string;
  articleResultAdditionalAttributes?: Array<string> | undefined;
  filterTags?: string | undefined;
  workflowMilestone?: string | undefined;
  language?: string | undefined;
  pagenum: number;
  pagesize: number;
  sort?: string | undefined;
  order?: string | undefined;
};

/** @internal */
export const GetArticlesInTopicRequest$outboundSchema: z.ZodType<
  GetArticlesInTopicRequest$Outbound,
  z.ZodTypeDef,
  GetArticlesInTopicRequest
> = z.object({
  acceptLanguage: models.AcceptLanguage$outboundSchema,
  portalID: z.string(),
  searchProfileId: z.string().optional(),
  filterTopicId: z.string(),
  articleResultAdditionalAttributes: z.array(
    models.ArticleResultAdditionalAttributes$outboundSchema,
  ).optional(),
  filterTags: z.string().optional(),
  workflowMilestone: models.WorkflowMilestone$outboundSchema.optional(),
  language: models.LanguageQueryParameter$outboundSchema.optional(),
  pagenum: z.number().int().default(1),
  pagesize: z.number().int().default(10),
  sort: models.ArticleSort$outboundSchema.optional(),
  order: models.ArticleSortOrder$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    acceptLanguage: "Accept-Language",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetArticlesInTopicRequest$ {
  /** @deprecated use `GetArticlesInTopicRequest$inboundSchema` instead. */
  export const inboundSchema = GetArticlesInTopicRequest$inboundSchema;
  /** @deprecated use `GetArticlesInTopicRequest$outboundSchema` instead. */
  export const outboundSchema = GetArticlesInTopicRequest$outboundSchema;
  /** @deprecated use `GetArticlesInTopicRequest$Outbound` instead. */
  export type Outbound = GetArticlesInTopicRequest$Outbound;
}

export function getArticlesInTopicRequestToJSON(
  getArticlesInTopicRequest: GetArticlesInTopicRequest,
): string {
  return JSON.stringify(
    GetArticlesInTopicRequest$outboundSchema.parse(getArticlesInTopicRequest),
  );
}

export function getArticlesInTopicRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetArticlesInTopicRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetArticlesInTopicRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetArticlesInTopicRequest' from JSON`,
  );
}
