/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetAttachmentByIdInPortalRequest = {
  /**
   * The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses).
   */
  acceptLanguage: models.AcceptLanguage;
  /**
   * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  portalID: string;
  /**
   * The ID of the attachment.<br><br>An attachment ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  attachmentID: string;
  /**
   * The language that describes the details of a resource. Resources available in different languages may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default language is used.</li>
   */
  language?: models.LanguageQueryParameter | undefined;
};

/** @internal */
export const GetAttachmentByIdInPortalRequest$inboundSchema: z.ZodType<
  GetAttachmentByIdInPortalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "Accept-Language": models.AcceptLanguage$inboundSchema,
  portalID: z.string(),
  attachmentID: z.string(),
  language: models.LanguageQueryParameter$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "Accept-Language": "acceptLanguage",
  });
});

/** @internal */
export type GetAttachmentByIdInPortalRequest$Outbound = {
  "Accept-Language": string;
  portalID: string;
  attachmentID: string;
  language?: string | undefined;
};

/** @internal */
export const GetAttachmentByIdInPortalRequest$outboundSchema: z.ZodType<
  GetAttachmentByIdInPortalRequest$Outbound,
  z.ZodTypeDef,
  GetAttachmentByIdInPortalRequest
> = z.object({
  acceptLanguage: models.AcceptLanguage$outboundSchema,
  portalID: z.string(),
  attachmentID: z.string(),
  language: models.LanguageQueryParameter$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    acceptLanguage: "Accept-Language",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAttachmentByIdInPortalRequest$ {
  /** @deprecated use `GetAttachmentByIdInPortalRequest$inboundSchema` instead. */
  export const inboundSchema = GetAttachmentByIdInPortalRequest$inboundSchema;
  /** @deprecated use `GetAttachmentByIdInPortalRequest$outboundSchema` instead. */
  export const outboundSchema = GetAttachmentByIdInPortalRequest$outboundSchema;
  /** @deprecated use `GetAttachmentByIdInPortalRequest$Outbound` instead. */
  export type Outbound = GetAttachmentByIdInPortalRequest$Outbound;
}

export function getAttachmentByIdInPortalRequestToJSON(
  getAttachmentByIdInPortalRequest: GetAttachmentByIdInPortalRequest,
): string {
  return JSON.stringify(
    GetAttachmentByIdInPortalRequest$outboundSchema.parse(
      getAttachmentByIdInPortalRequest,
    ),
  );
}

export function getAttachmentByIdInPortalRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAttachmentByIdInPortalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAttachmentByIdInPortalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAttachmentByIdInPortalRequest' from JSON`,
  );
}
