/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetArticleRatingsRequest = {
  /**
   * The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses).
   */
  acceptLanguage: models.AcceptLanguage;
  /**
   * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  portalID: string;
  /**
   * The ID of the Article.<br><br>An Article ID is composed of a 2-4 letter prefix followed by a dash and 4-15 digits.
   */
  articleID: string;
  /**
   * The language that describes the details of a resource. Resources available in different languages may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default language is used.</li>
   */
  language?: models.LanguageQueryParameter | undefined;
  /**
   * Pagination parameter that specifies the page number of results to be returned. Used in conjunction with $pagesize.
   */
  pagenum?: number | undefined;
  /**
   * Pagination parameter that specifies the number of results per page. Used in conjunction with $pagenum.
   */
  pagesize?: number | undefined;
};

/** @internal */
export const GetArticleRatingsRequest$inboundSchema: z.ZodType<
  GetArticleRatingsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "Accept-Language": models.AcceptLanguage$inboundSchema,
  portalID: z.string(),
  articleID: z.string(),
  language: models.LanguageQueryParameter$inboundSchema.optional(),
  pagenum: z.number().int().default(1),
  pagesize: z.number().int().default(10),
}).transform((v) => {
  return remap$(v, {
    "Accept-Language": "acceptLanguage",
  });
});

/** @internal */
export type GetArticleRatingsRequest$Outbound = {
  "Accept-Language": string;
  portalID: string;
  articleID: string;
  language?: string | undefined;
  pagenum: number;
  pagesize: number;
};

/** @internal */
export const GetArticleRatingsRequest$outboundSchema: z.ZodType<
  GetArticleRatingsRequest$Outbound,
  z.ZodTypeDef,
  GetArticleRatingsRequest
> = z.object({
  acceptLanguage: models.AcceptLanguage$outboundSchema,
  portalID: z.string(),
  articleID: z.string(),
  language: models.LanguageQueryParameter$outboundSchema.optional(),
  pagenum: z.number().int().default(1),
  pagesize: z.number().int().default(10),
}).transform((v) => {
  return remap$(v, {
    acceptLanguage: "Accept-Language",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetArticleRatingsRequest$ {
  /** @deprecated use `GetArticleRatingsRequest$inboundSchema` instead. */
  export const inboundSchema = GetArticleRatingsRequest$inboundSchema;
  /** @deprecated use `GetArticleRatingsRequest$outboundSchema` instead. */
  export const outboundSchema = GetArticleRatingsRequest$outboundSchema;
  /** @deprecated use `GetArticleRatingsRequest$Outbound` instead. */
  export type Outbound = GetArticleRatingsRequest$Outbound;
}

export function getArticleRatingsRequestToJSON(
  getArticleRatingsRequest: GetArticleRatingsRequest,
): string {
  return JSON.stringify(
    GetArticleRatingsRequest$outboundSchema.parse(getArticleRatingsRequest),
  );
}

export function getArticleRatingsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetArticleRatingsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetArticleRatingsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetArticleRatingsRequest' from JSON`,
  );
}
