/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetAllArticleTypesRequest = {
  /**
   * The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses).
   */
  acceptLanguage: models.AcceptLanguage;
  /**
   * The ID of the department.
   */
  departmentID: string;
};

/** @internal */
export const GetAllArticleTypesRequest$inboundSchema: z.ZodType<
  GetAllArticleTypesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "Accept-Language": models.AcceptLanguage$inboundSchema,
  departmentID: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Accept-Language": "acceptLanguage",
  });
});

/** @internal */
export type GetAllArticleTypesRequest$Outbound = {
  "Accept-Language": string;
  departmentID: string;
};

/** @internal */
export const GetAllArticleTypesRequest$outboundSchema: z.ZodType<
  GetAllArticleTypesRequest$Outbound,
  z.ZodTypeDef,
  GetAllArticleTypesRequest
> = z.object({
  acceptLanguage: models.AcceptLanguage$outboundSchema,
  departmentID: z.string(),
}).transform((v) => {
  return remap$(v, {
    acceptLanguage: "Accept-Language",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllArticleTypesRequest$ {
  /** @deprecated use `GetAllArticleTypesRequest$inboundSchema` instead. */
  export const inboundSchema = GetAllArticleTypesRequest$inboundSchema;
  /** @deprecated use `GetAllArticleTypesRequest$outboundSchema` instead. */
  export const outboundSchema = GetAllArticleTypesRequest$outboundSchema;
  /** @deprecated use `GetAllArticleTypesRequest$Outbound` instead. */
  export type Outbound = GetAllArticleTypesRequest$Outbound;
}

export function getAllArticleTypesRequestToJSON(
  getAllArticleTypesRequest: GetAllArticleTypesRequest,
): string {
  return JSON.stringify(
    GetAllArticleTypesRequest$outboundSchema.parse(getAllArticleTypesRequest),
  );
}

export function getAllArticleTypesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAllArticleTypesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllArticleTypesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllArticleTypesRequest' from JSON`,
  );
}
