/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const GetBestAnswerServerList = [
  /**
   * aiservices
   */
  "https://api.aidev.egain.cloud/core/aiservices/v4",
] as const;

export type GetBestAnswerRequest = {
  /**
   * The search query string. The string must be escaped as required by the URL syntax rules.
   */
  q: string;
  /**
   * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  portalID: string;
  filterUserProfileID?: string | undefined;
  /**
   * The language that describes the details of a resource. Resources available in different languages may differ from each other. <br><br> If lang is not passed, then the portal's default language is used.
   */
  language: models.LanguageCodeParameter;
  /**
   * An object where each key is a **Category Tag ID** (numeric string),
   *
   * @remarks
   * and each value is an array of **Tag IDs** for that category.
   */
  filterTags?: { [k: string]: Array<string> } | undefined;
  /**
   * An array of topic IDs. It is used to restrict search results to specific topics.
   */
  filterTopicIds?: Array<string> | undefined;
  answersRequest?: models.AnswersRequest | undefined;
};

/** @internal */
export const GetBestAnswerRequest$inboundSchema: z.ZodType<
  GetBestAnswerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  q: z.string(),
  portalID: z.string(),
  filterUserProfileID: z.string().optional(),
  language: models.LanguageCodeParameter$inboundSchema,
  filterTags: z.record(z.array(z.string())).optional(),
  filterTopicIds: z.array(z.string()).optional(),
  AnswersRequest: models.AnswersRequest$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "AnswersRequest": "answersRequest",
  });
});

/** @internal */
export type GetBestAnswerRequest$Outbound = {
  q: string;
  portalID: string;
  filterUserProfileID?: string | undefined;
  language: string;
  filterTags?: { [k: string]: Array<string> } | undefined;
  filterTopicIds?: Array<string> | undefined;
  AnswersRequest?: models.AnswersRequest$Outbound | undefined;
};

/** @internal */
export const GetBestAnswerRequest$outboundSchema: z.ZodType<
  GetBestAnswerRequest$Outbound,
  z.ZodTypeDef,
  GetBestAnswerRequest
> = z.object({
  q: z.string(),
  portalID: z.string(),
  filterUserProfileID: z.string().optional(),
  language: models.LanguageCodeParameter$outboundSchema,
  filterTags: z.record(z.array(z.string())).optional(),
  filterTopicIds: z.array(z.string()).optional(),
  answersRequest: models.AnswersRequest$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    answersRequest: "AnswersRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBestAnswerRequest$ {
  /** @deprecated use `GetBestAnswerRequest$inboundSchema` instead. */
  export const inboundSchema = GetBestAnswerRequest$inboundSchema;
  /** @deprecated use `GetBestAnswerRequest$outboundSchema` instead. */
  export const outboundSchema = GetBestAnswerRequest$outboundSchema;
  /** @deprecated use `GetBestAnswerRequest$Outbound` instead. */
  export type Outbound = GetBestAnswerRequest$Outbound;
}

export function getBestAnswerRequestToJSON(
  getBestAnswerRequest: GetBestAnswerRequest,
): string {
  return JSON.stringify(
    GetBestAnswerRequest$outboundSchema.parse(getBestAnswerRequest),
  );
}

export function getBestAnswerRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetBestAnswerRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBestAnswerRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBestAnswerRequest' from JSON`,
  );
}
