/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetMySubscriptionRequest = {
  /**
   * The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses).
   */
  acceptLanguage: models.AcceptLanguage;
  /**
   * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  portalID: string;
  /**
   * For agents with the View Author Portal or View Staging Portal actions, this determines which version of the Article is returned.<li>'Authoring' returns the most recent version of an Article checked-in by an author.</li><li>'Staging' returns the updated version currently being processed in a workflow.</li><li>'Publish' returns the most recently published version.</li>
   */
  workflowMilestone?: models.WorkflowMilestone | undefined;
  /**
   * Pagination parameter that specifies the page number of results to be returned. Used in conjunction with $pagesize.
   */
  pagenum?: number | undefined;
  /**
   * Pagination parameter that specifies the number of results per page. Used in conjunction with $pagenum.
   */
  pagesize?: number | undefined;
  /**
   * The attributes of an Article to be returned *in addition to* the default list of attributes, listed below. Multiple additional attributes can be specified using a comma-separated list. Passing 'all' will return all attributes.
   *
   * @remarks
   *
   * #### Default Attributes
   * These Article attributes are always returned:
   *
   * | Name | Description
   * | ---- | -----------
   * | id | The ID of the Article.
   * | name  | The name of the Article.
   * | articleType | The Article Type and its attributes.
   * | createdBy | The ID, first name, middle name and last name of the user that created the Article.
   * | createdDate | The date that the Article was created.
   * | hasAttachments | True: The Article has one or more attachments.<br>False: The Article does not have any attachments.
   * | languageCode | The language code of the Article language.
   * | modifiedBy | The ID, first name, middle name and last name of the user that last modified the Article.
   * | modifiedDate | The date that the Article was last modified on.
   * | link | The link object, used to retrieve the details of the Article.
   * | versionId | The ID of the Article version that is returned.
   */
  articleResultAdditionalAttributes?:
    | Array<models.ArticleResultAdditionalAttributes>
    | undefined;
};

/** @internal */
export const GetMySubscriptionRequest$inboundSchema: z.ZodType<
  GetMySubscriptionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "Accept-Language": models.AcceptLanguage$inboundSchema,
  portalID: z.string(),
  workflowMilestone: models.WorkflowMilestone$inboundSchema.optional(),
  pagenum: z.number().int().default(1),
  pagesize: z.number().int().default(10),
  articleResultAdditionalAttributes: z.array(
    models.ArticleResultAdditionalAttributes$inboundSchema,
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "Accept-Language": "acceptLanguage",
  });
});

/** @internal */
export type GetMySubscriptionRequest$Outbound = {
  "Accept-Language": string;
  portalID: string;
  workflowMilestone?: string | undefined;
  pagenum: number;
  pagesize: number;
  articleResultAdditionalAttributes?: Array<string> | undefined;
};

/** @internal */
export const GetMySubscriptionRequest$outboundSchema: z.ZodType<
  GetMySubscriptionRequest$Outbound,
  z.ZodTypeDef,
  GetMySubscriptionRequest
> = z.object({
  acceptLanguage: models.AcceptLanguage$outboundSchema,
  portalID: z.string(),
  workflowMilestone: models.WorkflowMilestone$outboundSchema.optional(),
  pagenum: z.number().int().default(1),
  pagesize: z.number().int().default(10),
  articleResultAdditionalAttributes: z.array(
    models.ArticleResultAdditionalAttributes$outboundSchema,
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    acceptLanguage: "Accept-Language",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetMySubscriptionRequest$ {
  /** @deprecated use `GetMySubscriptionRequest$inboundSchema` instead. */
  export const inboundSchema = GetMySubscriptionRequest$inboundSchema;
  /** @deprecated use `GetMySubscriptionRequest$outboundSchema` instead. */
  export const outboundSchema = GetMySubscriptionRequest$outboundSchema;
  /** @deprecated use `GetMySubscriptionRequest$Outbound` instead. */
  export type Outbound = GetMySubscriptionRequest$Outbound;
}

export function getMySubscriptionRequestToJSON(
  getMySubscriptionRequest: GetMySubscriptionRequest,
): string {
  return JSON.stringify(
    GetMySubscriptionRequest$outboundSchema.parse(getMySubscriptionRequest),
  );
}

export function getMySubscriptionRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetMySubscriptionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMySubscriptionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMySubscriptionRequest' from JSON`,
  );
}
