/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetPortalDetailsByIdRequest = {
  /**
   * The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses).
   */
  acceptLanguage: models.AcceptLanguage;
  /**
   * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  portalID: string;
  /**
   * The language that describes the details of a resource. Resources available in different languages may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default language is used.</li>
   */
  language?: models.LanguageQueryParameter | undefined;
};

/** @internal */
export const GetPortalDetailsByIdRequest$inboundSchema: z.ZodType<
  GetPortalDetailsByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "Accept-Language": models.AcceptLanguage$inboundSchema,
  portalID: z.string(),
  language: models.LanguageQueryParameter$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "Accept-Language": "acceptLanguage",
  });
});

/** @internal */
export type GetPortalDetailsByIdRequest$Outbound = {
  "Accept-Language": string;
  portalID: string;
  language?: string | undefined;
};

/** @internal */
export const GetPortalDetailsByIdRequest$outboundSchema: z.ZodType<
  GetPortalDetailsByIdRequest$Outbound,
  z.ZodTypeDef,
  GetPortalDetailsByIdRequest
> = z.object({
  acceptLanguage: models.AcceptLanguage$outboundSchema,
  portalID: z.string(),
  language: models.LanguageQueryParameter$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    acceptLanguage: "Accept-Language",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPortalDetailsByIdRequest$ {
  /** @deprecated use `GetPortalDetailsByIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetPortalDetailsByIdRequest$inboundSchema;
  /** @deprecated use `GetPortalDetailsByIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetPortalDetailsByIdRequest$outboundSchema;
  /** @deprecated use `GetPortalDetailsByIdRequest$Outbound` instead. */
  export type Outbound = GetPortalDetailsByIdRequest$Outbound;
}

export function getPortalDetailsByIdRequestToJSON(
  getPortalDetailsByIdRequest: GetPortalDetailsByIdRequest,
): string {
  return JSON.stringify(
    GetPortalDetailsByIdRequest$outboundSchema.parse(
      getPortalDetailsByIdRequest,
    ),
  );
}

export function getPortalDetailsByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetPortalDetailsByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPortalDetailsByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPortalDetailsByIdRequest' from JSON`,
  );
}
