/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetSuggestionAttachmentByIdRequest = {
  /**
   * The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses).
   */
  acceptLanguage: models.AcceptLanguage;
  /**
   * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  portalID: string;
  /**
   * The ID of the attachment.<br><br>An attachment ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  attachmentID: string;
  /**
   * The attributes of an attachment to be returned, along with the default attachment details.
   *
   * @remarks
   *
   * | Attribute    | Description                        |
   * |--------------|------------------------------------|
   * | id         | Unique identifier for the attachment |
   * | fileName   | Name of the file                   |
   * | contentType| Content type of the file              |
   * | size       | Size of the file in bytes          |
   * | link       | Link to the attachment             |
   */
  attachmentAdditionalAttributes?:
    | Array<models.AttachmentAdditionalAttributes>
    | undefined;
};

/** @internal */
export const GetSuggestionAttachmentByIdRequest$inboundSchema: z.ZodType<
  GetSuggestionAttachmentByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "Accept-Language": models.AcceptLanguage$inboundSchema,
  portalID: z.string(),
  attachmentID: z.string(),
  attachmentAdditionalAttributes: z.array(
    models.AttachmentAdditionalAttributes$inboundSchema,
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "Accept-Language": "acceptLanguage",
  });
});

/** @internal */
export type GetSuggestionAttachmentByIdRequest$Outbound = {
  "Accept-Language": string;
  portalID: string;
  attachmentID: string;
  attachmentAdditionalAttributes?: Array<string> | undefined;
};

/** @internal */
export const GetSuggestionAttachmentByIdRequest$outboundSchema: z.ZodType<
  GetSuggestionAttachmentByIdRequest$Outbound,
  z.ZodTypeDef,
  GetSuggestionAttachmentByIdRequest
> = z.object({
  acceptLanguage: models.AcceptLanguage$outboundSchema,
  portalID: z.string(),
  attachmentID: z.string(),
  attachmentAdditionalAttributes: z.array(
    models.AttachmentAdditionalAttributes$outboundSchema,
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    acceptLanguage: "Accept-Language",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSuggestionAttachmentByIdRequest$ {
  /** @deprecated use `GetSuggestionAttachmentByIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetSuggestionAttachmentByIdRequest$inboundSchema;
  /** @deprecated use `GetSuggestionAttachmentByIdRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetSuggestionAttachmentByIdRequest$outboundSchema;
  /** @deprecated use `GetSuggestionAttachmentByIdRequest$Outbound` instead. */
  export type Outbound = GetSuggestionAttachmentByIdRequest$Outbound;
}

export function getSuggestionAttachmentByIdRequestToJSON(
  getSuggestionAttachmentByIdRequest: GetSuggestionAttachmentByIdRequest,
): string {
  return JSON.stringify(
    GetSuggestionAttachmentByIdRequest$outboundSchema.parse(
      getSuggestionAttachmentByIdRequest,
    ),
  );
}

export function getSuggestionAttachmentByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetSuggestionAttachmentByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetSuggestionAttachmentByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSuggestionAttachmentByIdRequest' from JSON`,
  );
}
