/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const GetValidationHookVersionServerList = [
  /**
   * Production Server
   */
  "https://api.aidev.egain.cloud//knowledge/contentmgr/v4",
] as const;

export type GetValidationHookVersionRequest = {
  /**
   * Integer ID of the Hook resource.
   */
  hookID: number;
  /**
   * The sequential version number of the hook (e.g., 1, 2, 3).
   */
  versionID: number;
};

/** @internal */
export const GetValidationHookVersionRequest$inboundSchema: z.ZodType<
  GetValidationHookVersionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  hookID: z.number().int(),
  versionID: z.number().int(),
});

/** @internal */
export type GetValidationHookVersionRequest$Outbound = {
  hookID: number;
  versionID: number;
};

/** @internal */
export const GetValidationHookVersionRequest$outboundSchema: z.ZodType<
  GetValidationHookVersionRequest$Outbound,
  z.ZodTypeDef,
  GetValidationHookVersionRequest
> = z.object({
  hookID: z.number().int(),
  versionID: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetValidationHookVersionRequest$ {
  /** @deprecated use `GetValidationHookVersionRequest$inboundSchema` instead. */
  export const inboundSchema = GetValidationHookVersionRequest$inboundSchema;
  /** @deprecated use `GetValidationHookVersionRequest$outboundSchema` instead. */
  export const outboundSchema = GetValidationHookVersionRequest$outboundSchema;
  /** @deprecated use `GetValidationHookVersionRequest$Outbound` instead. */
  export type Outbound = GetValidationHookVersionRequest$Outbound;
}

export function getValidationHookVersionRequestToJSON(
  getValidationHookVersionRequest: GetValidationHookVersionRequest,
): string {
  return JSON.stringify(
    GetValidationHookVersionRequest$outboundSchema.parse(
      getValidationHookVersionRequest,
    ),
  );
}

export function getValidationHookVersionRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetValidationHookVersionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetValidationHookVersionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetValidationHookVersionRequest' from JSON`,
  );
}
