/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The type of the Article and its attributes.
 */
export type ArticleType = {
  /**
   * Specifies the article category ID.
   */
  articleCategoryId?: number | undefined;
  /**
   * Indicates the article type name.
   */
  typeName?: string | undefined;
  /**
   * Indicates whether structured authoring is enabled for this article type, requiring content to be created using predefined fields
   */
  useStructuredAuthoring?: boolean | undefined;
  /**
   * The ID of the Article Type.
   */
  articleTypeId?: string | undefined;
};

/** @internal */
export const ArticleType$inboundSchema: z.ZodType<
  ArticleType,
  z.ZodTypeDef,
  unknown
> = z.object({
  articleCategoryId: z.number().int().optional(),
  typeName: z.string().optional(),
  useStructuredAuthoring: z.boolean().optional(),
  articleTypeId: z.string().optional(),
});

/** @internal */
export type ArticleType$Outbound = {
  articleCategoryId?: number | undefined;
  typeName?: string | undefined;
  useStructuredAuthoring?: boolean | undefined;
  articleTypeId?: string | undefined;
};

/** @internal */
export const ArticleType$outboundSchema: z.ZodType<
  ArticleType$Outbound,
  z.ZodTypeDef,
  ArticleType
> = z.object({
  articleCategoryId: z.number().int().optional(),
  typeName: z.string().optional(),
  useStructuredAuthoring: z.boolean().optional(),
  articleTypeId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ArticleType$ {
  /** @deprecated use `ArticleType$inboundSchema` instead. */
  export const inboundSchema = ArticleType$inboundSchema;
  /** @deprecated use `ArticleType$outboundSchema` instead. */
  export const outboundSchema = ArticleType$outboundSchema;
  /** @deprecated use `ArticleType$Outbound` instead. */
  export type Outbound = ArticleType$Outbound;
}

export function articleTypeToJSON(articleType: ArticleType): string {
  return JSON.stringify(ArticleType$outboundSchema.parse(articleType));
}

export function articleTypeFromJSON(
  jsonString: string,
): SafeParseResult<ArticleType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ArticleType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ArticleType' from JSON`,
  );
}
