/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Link,
  Link$inboundSchema,
  Link$Outbound,
  Link$outboundSchema,
} from "./link.js";

export type ArticleListResult = {
  /**
   * The name of the article list.
   */
  name: string;
  /**
   * The ID of the article list.<br><br>An article list ID is either a 4-digit number or composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  id: string;
  /**
   * The description of the article list. The maximum allowed article list description size is 1 KB.
   */
  description?: string | undefined;
  /**
   * The type of the article list.
   */
  typeId?: string | undefined;
  /**
   * Defines the relationship between this resource and another object.
   */
  link?: Link | undefined;
};

/** @internal */
export const ArticleListResult$inboundSchema: z.ZodType<
  ArticleListResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  id: z.string(),
  description: z.string().optional(),
  typeId: z.string().optional(),
  link: Link$inboundSchema.optional(),
});

/** @internal */
export type ArticleListResult$Outbound = {
  name: string;
  id: string;
  description?: string | undefined;
  typeId?: string | undefined;
  link?: Link$Outbound | undefined;
};

/** @internal */
export const ArticleListResult$outboundSchema: z.ZodType<
  ArticleListResult$Outbound,
  z.ZodTypeDef,
  ArticleListResult
> = z.object({
  name: z.string(),
  id: z.string(),
  description: z.string().optional(),
  typeId: z.string().optional(),
  link: Link$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ArticleListResult$ {
  /** @deprecated use `ArticleListResult$inboundSchema` instead. */
  export const inboundSchema = ArticleListResult$inboundSchema;
  /** @deprecated use `ArticleListResult$outboundSchema` instead. */
  export const outboundSchema = ArticleListResult$outboundSchema;
  /** @deprecated use `ArticleListResult$Outbound` instead. */
  export type Outbound = ArticleListResult$Outbound;
}

export function articleListResultToJSON(
  articleListResult: ArticleListResult,
): string {
  return JSON.stringify(
    ArticleListResult$outboundSchema.parse(articleListResult),
  );
}

export function articleListResultFromJSON(
  jsonString: string,
): SafeParseResult<ArticleListResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ArticleListResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ArticleListResult' from JSON`,
  );
}
