/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Sort order of articles.
 */
export const ArticleSortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * Sort order of articles.
 */
export type ArticleSortOrder = ClosedEnum<typeof ArticleSortOrder>;

/** @internal */
export const ArticleSortOrder$inboundSchema: z.ZodNativeEnum<
  typeof ArticleSortOrder
> = z.nativeEnum(ArticleSortOrder);

/** @internal */
export const ArticleSortOrder$outboundSchema: z.ZodNativeEnum<
  typeof ArticleSortOrder
> = ArticleSortOrder$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ArticleSortOrder$ {
  /** @deprecated use `ArticleSortOrder$inboundSchema` instead. */
  export const inboundSchema = ArticleSortOrder$inboundSchema;
  /** @deprecated use `ArticleSortOrder$outboundSchema` instead. */
  export const outboundSchema = ArticleSortOrder$outboundSchema;
}
