/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ArticleResultAdditionalAttributes = {
  AverageRating: "averageRating",
  CustomAttributes: "customAttributes",
  Description: "description",
  ArticleSummary: "articleSummary",
  ImageURL: "imageURL",
  IsSubscribed: "isSubscribed",
  TimesRated: "timesRated",
  TopicBreadcrumb: "topicBreadcrumb",
  OwnedBy: "ownedBy",
  OwnedByUserName: "ownedBy.userName",
  Workflow: "workflow",
  Compliance: "compliance",
  Personalization: "personalization",
  All: "all",
} as const;
export type ArticleResultAdditionalAttributes = ClosedEnum<
  typeof ArticleResultAdditionalAttributes
>;

/** @internal */
export const ArticleResultAdditionalAttributes$inboundSchema: z.ZodNativeEnum<
  typeof ArticleResultAdditionalAttributes
> = z.nativeEnum(ArticleResultAdditionalAttributes);

/** @internal */
export const ArticleResultAdditionalAttributes$outboundSchema: z.ZodNativeEnum<
  typeof ArticleResultAdditionalAttributes
> = ArticleResultAdditionalAttributes$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ArticleResultAdditionalAttributes$ {
  /** @deprecated use `ArticleResultAdditionalAttributes$inboundSchema` instead. */
  export const inboundSchema = ArticleResultAdditionalAttributes$inboundSchema;
  /** @deprecated use `ArticleResultAdditionalAttributes$outboundSchema` instead. */
  export const outboundSchema =
    ArticleResultAdditionalAttributes$outboundSchema;
}
