/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Success
 */
export type ArticleTypeInfo = {
  /**
   * Specifies the article category ID.
   */
  articleCategoryId?: number | undefined;
  /**
   * Indicates the article type name.
   */
  typeName?: string | undefined;
  /**
   * Indicates whether structured authoring is enabled for this article type, requiring content to be created using predefined fields
   */
  useStructuredAuthoring?: boolean | undefined;
  /**
   * The ID of the Article Type.
   */
  articleTypeId?: string | undefined;
  /**
   * The URL of an image to be associated with the Article Type
   */
  imageURL?: string | undefined;
  /**
   * Description of Article Type
   */
  description?: string | undefined;
  /**
   * Indicates whether articles of this type are included in portal search results
   */
  isSearchable?: boolean | undefined;
  /**
   * Indicates whether articles of this type are displayed in portal browsing areas such as topics and lists
   */
  isBrowsable?: boolean | undefined;
};

/** @internal */
export const ArticleTypeInfo$inboundSchema: z.ZodType<
  ArticleTypeInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  articleCategoryId: z.number().int().optional(),
  typeName: z.string().optional(),
  useStructuredAuthoring: z.boolean().optional(),
  articleTypeId: z.string().optional(),
  imageURL: z.string().optional(),
  description: z.string().optional(),
  isSearchable: z.boolean().optional(),
  isBrowsable: z.boolean().optional(),
});

/** @internal */
export type ArticleTypeInfo$Outbound = {
  articleCategoryId?: number | undefined;
  typeName?: string | undefined;
  useStructuredAuthoring?: boolean | undefined;
  articleTypeId?: string | undefined;
  imageURL?: string | undefined;
  description?: string | undefined;
  isSearchable?: boolean | undefined;
  isBrowsable?: boolean | undefined;
};

/** @internal */
export const ArticleTypeInfo$outboundSchema: z.ZodType<
  ArticleTypeInfo$Outbound,
  z.ZodTypeDef,
  ArticleTypeInfo
> = z.object({
  articleCategoryId: z.number().int().optional(),
  typeName: z.string().optional(),
  useStructuredAuthoring: z.boolean().optional(),
  articleTypeId: z.string().optional(),
  imageURL: z.string().optional(),
  description: z.string().optional(),
  isSearchable: z.boolean().optional(),
  isBrowsable: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ArticleTypeInfo$ {
  /** @deprecated use `ArticleTypeInfo$inboundSchema` instead. */
  export const inboundSchema = ArticleTypeInfo$inboundSchema;
  /** @deprecated use `ArticleTypeInfo$outboundSchema` instead. */
  export const outboundSchema = ArticleTypeInfo$outboundSchema;
  /** @deprecated use `ArticleTypeInfo$Outbound` instead. */
  export type Outbound = ArticleTypeInfo$Outbound;
}

export function articleTypeInfoToJSON(
  articleTypeInfo: ArticleTypeInfo,
): string {
  return JSON.stringify(ArticleTypeInfo$outboundSchema.parse(articleTypeInfo));
}

export function articleTypeInfoFromJSON(
  jsonString: string,
): SafeParseResult<ArticleTypeInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ArticleTypeInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ArticleTypeInfo' from JSON`,
  );
}
