/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DataSourceCredentials = {
  /**
   * Access key for S3 credentials datasource. Provide along with Secret Key.
   */
  accessKey?: string | undefined;
  /**
   * Secret key for S3 credentials datasource. Provide along with Access Key.
   */
  secretKey?: string | undefined;
  /**
   * Username for SFTP credentials datasource. Provide along with Password.
   */
  username?: string | undefined;
  /**
   * Password for SFTP credentials datasource. Provide along with Username.
   */
  password?: string | undefined;
};

/** @internal */
export const DataSourceCredentials$inboundSchema: z.ZodType<
  DataSourceCredentials,
  z.ZodTypeDef,
  unknown
> = z.object({
  accessKey: z.string().optional(),
  secretKey: z.string().optional(),
  username: z.string().optional(),
  password: z.string().optional(),
});

/** @internal */
export type DataSourceCredentials$Outbound = {
  accessKey?: string | undefined;
  secretKey?: string | undefined;
  username?: string | undefined;
  password?: string | undefined;
};

/** @internal */
export const DataSourceCredentials$outboundSchema: z.ZodType<
  DataSourceCredentials$Outbound,
  z.ZodTypeDef,
  DataSourceCredentials
> = z.object({
  accessKey: z.string().optional(),
  secretKey: z.string().optional(),
  username: z.string().optional(),
  password: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DataSourceCredentials$ {
  /** @deprecated use `DataSourceCredentials$inboundSchema` instead. */
  export const inboundSchema = DataSourceCredentials$inboundSchema;
  /** @deprecated use `DataSourceCredentials$outboundSchema` instead. */
  export const outboundSchema = DataSourceCredentials$outboundSchema;
  /** @deprecated use `DataSourceCredentials$Outbound` instead. */
  export type Outbound = DataSourceCredentials$Outbound;
}

export function dataSourceCredentialsToJSON(
  dataSourceCredentials: DataSourceCredentials,
): string {
  return JSON.stringify(
    DataSourceCredentials$outboundSchema.parse(dataSourceCredentials),
  );
}

export function dataSourceCredentialsFromJSON(
  jsonString: string,
): SafeParseResult<DataSourceCredentials, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DataSourceCredentials$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DataSourceCredentials' from JSON`,
  );
}
