/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Replacement,
  Replacement$inboundSchema,
  Replacement$Outbound,
  Replacement$outboundSchema,
} from "./replacement.js";

/**
 * The language used for the prompt template.
 */
export const LanguageCodeRequestBody = {
  EnUS: "en-US",
  FRFR: "fr-FR",
  EnGB: "en-GB",
  ESES: "es-ES",
  ITIT: "it-IT",
  NLNL: "nl-NL",
  DADA: "da-DA",
  SvSE: "sv-SE",
  PTPT: "pt-PT",
  FIFI: "fi-FI",
  NoNB: "no-NB",
  NoNN: "no-NN",
  JAJA: "ja-JA",
  DEDE: "de-DE",
  PtBR: "pt-BR",
  ZhCN: "zh-CN",
  ZhTW: "zh-TW",
  KOKO: "ko-KO",
  RURU: "ru-RU",
  ELEL: "el-EL",
  TRTR: "tr-TR",
  PLPL: "pl-PL",
  CSCS: "cs-CS",
  SKSK: "sk-SK",
  HUHU: "hu-HU",
  SRSR: "sr-SR",
  ArSA: "ar-SA",
  HRHR: "hr-HR",
  RORO: "ro-RO",
  THTH: "th-TH",
  XXXX: "xx-XX",
} as const;
/**
 * The language used for the prompt template.
 */
export type LanguageCodeRequestBody = ClosedEnum<
  typeof LanguageCodeRequestBody
>;

/**
 * Event type logged when the API executes successfully.
 */
export const EventTypeRequestBody = {
  Generate: "generate",
  Regenerate: "regenerate",
} as const;
/**
 * Event type logged when the API executes successfully.
 */
export type EventTypeRequestBody = ClosedEnum<typeof EventTypeRequestBody>;

export type ExecutePrompt = {
  /**
   * Name of the department. Must be a valid department name.
   */
  department: string;
  /**
   * The language used for the prompt template.
   */
  languageCode: LanguageCodeRequestBody;
  /**
   * List of variable replacements (either static or search).
   */
  replacements?: Array<Replacement> | undefined;
  /**
   * Event type logged when the API executes successfully.
   */
  eventType?: EventTypeRequestBody | undefined;
  /**
   * Client provided sessionID to store events against.
   */
  clientSessionId?: string | undefined;
  /**
   * Whether to stream the response instead of returning inline.
   */
  streaming?: boolean | undefined;
};

/** @internal */
export const LanguageCodeRequestBody$inboundSchema: z.ZodNativeEnum<
  typeof LanguageCodeRequestBody
> = z.nativeEnum(LanguageCodeRequestBody);

/** @internal */
export const LanguageCodeRequestBody$outboundSchema: z.ZodNativeEnum<
  typeof LanguageCodeRequestBody
> = LanguageCodeRequestBody$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LanguageCodeRequestBody$ {
  /** @deprecated use `LanguageCodeRequestBody$inboundSchema` instead. */
  export const inboundSchema = LanguageCodeRequestBody$inboundSchema;
  /** @deprecated use `LanguageCodeRequestBody$outboundSchema` instead. */
  export const outboundSchema = LanguageCodeRequestBody$outboundSchema;
}

/** @internal */
export const EventTypeRequestBody$inboundSchema: z.ZodNativeEnum<
  typeof EventTypeRequestBody
> = z.nativeEnum(EventTypeRequestBody);

/** @internal */
export const EventTypeRequestBody$outboundSchema: z.ZodNativeEnum<
  typeof EventTypeRequestBody
> = EventTypeRequestBody$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EventTypeRequestBody$ {
  /** @deprecated use `EventTypeRequestBody$inboundSchema` instead. */
  export const inboundSchema = EventTypeRequestBody$inboundSchema;
  /** @deprecated use `EventTypeRequestBody$outboundSchema` instead. */
  export const outboundSchema = EventTypeRequestBody$outboundSchema;
}

/** @internal */
export const ExecutePrompt$inboundSchema: z.ZodType<
  ExecutePrompt,
  z.ZodTypeDef,
  unknown
> = z.object({
  department: z.string(),
  languageCode: LanguageCodeRequestBody$inboundSchema,
  replacements: z.array(Replacement$inboundSchema).optional(),
  eventType: EventTypeRequestBody$inboundSchema.default("generate"),
  clientSessionId: z.string().optional(),
  streaming: z.boolean().default(false),
});

/** @internal */
export type ExecutePrompt$Outbound = {
  department: string;
  languageCode: string;
  replacements?: Array<Replacement$Outbound> | undefined;
  eventType: string;
  clientSessionId?: string | undefined;
  streaming: boolean;
};

/** @internal */
export const ExecutePrompt$outboundSchema: z.ZodType<
  ExecutePrompt$Outbound,
  z.ZodTypeDef,
  ExecutePrompt
> = z.object({
  department: z.string(),
  languageCode: LanguageCodeRequestBody$outboundSchema,
  replacements: z.array(Replacement$outboundSchema).optional(),
  eventType: EventTypeRequestBody$outboundSchema.default("generate"),
  clientSessionId: z.string().optional(),
  streaming: z.boolean().default(false),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExecutePrompt$ {
  /** @deprecated use `ExecutePrompt$inboundSchema` instead. */
  export const inboundSchema = ExecutePrompt$inboundSchema;
  /** @deprecated use `ExecutePrompt$outboundSchema` instead. */
  export const outboundSchema = ExecutePrompt$outboundSchema;
  /** @deprecated use `ExecutePrompt$Outbound` instead. */
  export type Outbound = ExecutePrompt$Outbound;
}

export function executePromptToJSON(executePrompt: ExecutePrompt): string {
  return JSON.stringify(ExecutePrompt$outboundSchema.parse(executePrompt));
}

export function executePromptFromJSON(
  jsonString: string,
): SafeParseResult<ExecutePrompt, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExecutePrompt$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExecutePrompt' from JSON`,
  );
}
