/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  FileObject,
  FileObject$inboundSchema,
  FileObject$Outbound,
  FileObject$outboundSchema,
} from "./fileobject.js";

export const HookType = {
  ImportPreValidationHook: "import_pre_validation_hook",
  ImportPostValidationHook: "import_post_validation_hook",
} as const;
export type HookType = ClosedEnum<typeof HookType>;

export type Hook = {
  /**
   * ID of hook
   */
  hookID?: number | undefined;
  /**
   * Name of the hook.
   */
  name?: string | undefined;
  type: HookType;
  fileObject: FileObject;
};

/** @internal */
export const HookType$inboundSchema: z.ZodNativeEnum<typeof HookType> = z
  .nativeEnum(HookType);

/** @internal */
export const HookType$outboundSchema: z.ZodNativeEnum<typeof HookType> =
  HookType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace HookType$ {
  /** @deprecated use `HookType$inboundSchema` instead. */
  export const inboundSchema = HookType$inboundSchema;
  /** @deprecated use `HookType$outboundSchema` instead. */
  export const outboundSchema = HookType$outboundSchema;
}

/** @internal */
export const Hook$inboundSchema: z.ZodType<Hook, z.ZodTypeDef, unknown> = z
  .object({
    hookID: z.number().int().optional(),
    name: z.string().optional(),
    type: HookType$inboundSchema,
    fileObject: FileObject$inboundSchema,
  });

/** @internal */
export type Hook$Outbound = {
  hookID?: number | undefined;
  name?: string | undefined;
  type: string;
  fileObject: FileObject$Outbound;
};

/** @internal */
export const Hook$outboundSchema: z.ZodType<Hook$Outbound, z.ZodTypeDef, Hook> =
  z.object({
    hookID: z.number().int().optional(),
    name: z.string().optional(),
    type: HookType$outboundSchema,
    fileObject: FileObject$outboundSchema,
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Hook$ {
  /** @deprecated use `Hook$inboundSchema` instead. */
  export const inboundSchema = Hook$inboundSchema;
  /** @deprecated use `Hook$outboundSchema` instead. */
  export const outboundSchema = Hook$outboundSchema;
  /** @deprecated use `Hook$Outbound` instead. */
  export type Outbound = Hook$Outbound;
}

export function hookToJSON(hook: Hook): string {
  return JSON.stringify(Hook$outboundSchema.parse(hook));
}

export function hookFromJSON(
  jsonString: string,
): SafeParseResult<Hook, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Hook$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Hook' from JSON`,
  );
}
