/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  S3Config,
  S3Config$inboundSchema,
  S3Config$Outbound,
  S3Config$outboundSchema,
} from "./s3config.js";
import {
  SftpConfig,
  SftpConfig$inboundSchema,
  SftpConfig$Outbound,
  SftpConfig$outboundSchema,
} from "./sftpconfig.js";

/**
 * Category of articles to return. If all is selected, it includes both browsable and searchable articles.
 */
export const ArticleCategories = {
  Searchable: "searchable",
  All: "all",
} as const;
/**
 * Category of articles to return. If all is selected, it includes both browsable and searchable articles.
 */
export type ArticleCategories = ClosedEnum<typeof ArticleCategories>;

/**
 * The code of the language.
 */
export const KnowledgeExportCode = {
  EnUS: "en-US",
  FRFR: "fr-FR",
  EnGB: "en-GB",
  ESES: "es-ES",
  ITIT: "it-IT",
  NLNL: "nl-NL",
  DADA: "da-DA",
  SvSE: "sv-SE",
  PTPT: "pt-PT",
  FIFI: "fi-FI",
  NoNB: "no-NB",
  NoNN: "no-NN",
  JAJA: "ja-JA",
  DEDE: "de-DE",
  PtBR: "pt-BR",
  ZhCN: "zh-CN",
  ZhTW: "zh-TW",
  KOKO: "ko-KO",
  RURU: "ru-RU",
  ELEL: "el-EL",
  TRTR: "tr-TR",
  PLPL: "pl-PL",
  CSCS: "cs-CS",
  SKSK: "sk-SK",
  HUHU: "hu-HU",
  SRSR: "sr-SR",
  ArSA: "ar-SA",
  HRHR: "hr-HR",
  RORO: "ro-RO",
  THTH: "th-TH",
  DeAT: "de-AT",
  ViVN: "vi-VN",
  IDID: "id-ID",
  MsMY: "ms-MY",
  FilPH: "fil-PH",
  FrCA: "fr-CA",
  HiIN: "hi-IN",
  UkUA: "uk-UA",
  BGBG: "bg-BG",
  SlSI: "sl-SI",
  XXXX: "xx-XX",
} as const;
/**
 * The code of the language.
 */
export type KnowledgeExportCode = ClosedEnum<typeof KnowledgeExportCode>;

/**
 * The Knowledge Base language in which the content is created.
 */
export type KnowledgeExportLanguage = {
  /**
   * The code of the language.
   */
  code: KnowledgeExportCode;
};

export const ResourceType = {
  Articles: "articles",
  Topics: "topics",
  Portals: "portals",
  All: "all",
} as const;
export type ResourceType = ClosedEnum<typeof ResourceType>;

/**
 * Type of data destination
 */
export const DestinationType = {
  AWSS3Bucket: "AWS S3 bucket",
  SFTPServer: "SFTP server",
} as const;
/**
 * Type of data destination
 */
export type DestinationType = ClosedEnum<typeof DestinationType>;

export type DataDestination = {
  /**
   * Type of data destination
   */
  destinationType: DestinationType;
  /**
   * Path of the data destination. For S3 bucket, it can be root or a folder. For SFTP, it can be target directory on the server.
   *
   * @remarks
   *
   * **Examples:**
   *
   * * **For S3:** `"s3://amzn-s3-demo-bucket/mydeptfolder"`
   * * **For SFTP:** `"exports/mydeptfolder"`
   */
  path: string;
  sftpDetails?: SftpConfig | undefined;
  s3Details?: S3Config | undefined;
};

export type KnowledgeExport = {
  /**
   * Category of articles to return. If all is selected, it includes both browsable and searchable articles.
   */
  articleCategories?: ArticleCategories | undefined;
  /**
   * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
   */
  portalID: string;
  /**
   * The Knowledge Base language in which the content is created.
   */
  language: KnowledgeExportLanguage;
  /**
   * Determines which article version to export. If true, the latest unpublished version will be exported for each article where available, and articles that do not have an unpublished version will be omitted from the export. If this property is false or omitted, the latest published version will be exported for each article where available. Each request exports either all published or all unpublished article versions in a portal; never both.
   */
  exportUnpublishedOnly?: boolean | undefined;
  /**
   * Types of Knowledge Hub resources to export. Use 'all' to specify all resource types at once.
   *
   * @remarks
   *
   * Below are the attributes that are returned for each resource type specified.
   *
   * ##### Portal Resource Type Attributes
   * Portal Attribute Name | Description
   * ------------------------------- | -----------
   * | id | The ID of the Portal in Readable format.
   * | alternateId | The system-generated ID of the Portal in long format.
   * | name  | The name of the Portal.
   * | description | The Portal's description.
   * | departmentId | ID of the department this Portal belongs to.
   * | defaultContentLanguageId | The default ID of the language for the portal content.
   *
   * ##### Topic Resource Type Attributes
   * | Topic Attribute Name | Description
   * | ------------------------------ | -----------
   * | id | The ID of the Topic in Readable form.
   * | alternateId | The system-generated ID of the Topic in long form.
   * | name  | The name of the Topic.
   * | departmentId | ID of the department this Topic belongs to.
   * | modifiedDate | The date when the Topic was last modified on.
   * | topicHomeArticleId | The ID of the Article used as the home page of this Topic.
   * | childCount | Total number of children sub-topis below the current Topic.
   * | subTopicIds | Array with the list of sub-topics (all levels of the topic hierarchy).
   * | parentTopicId | ID of the parent Topic. -1 if it is the root Topic.
   * | imageURL | URL of the inline Topic image.
   * | customAttributes | One or more comma-separated names for Topic custom attributes defined by the user to be returned.
   *
   * ##### Article Resource Type Attributes
   * Export article's attributes returned are aligned with the response of the [Get Article By ID with Editions](../article/getarticlebyidwitheditions) API.
   */
  resourceTypes: Array<ResourceType>;
  dataDestination: DataDestination;
};

/** @internal */
export const ArticleCategories$inboundSchema: z.ZodNativeEnum<
  typeof ArticleCategories
> = z.nativeEnum(ArticleCategories);

/** @internal */
export const ArticleCategories$outboundSchema: z.ZodNativeEnum<
  typeof ArticleCategories
> = ArticleCategories$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ArticleCategories$ {
  /** @deprecated use `ArticleCategories$inboundSchema` instead. */
  export const inboundSchema = ArticleCategories$inboundSchema;
  /** @deprecated use `ArticleCategories$outboundSchema` instead. */
  export const outboundSchema = ArticleCategories$outboundSchema;
}

/** @internal */
export const KnowledgeExportCode$inboundSchema: z.ZodNativeEnum<
  typeof KnowledgeExportCode
> = z.nativeEnum(KnowledgeExportCode);

/** @internal */
export const KnowledgeExportCode$outboundSchema: z.ZodNativeEnum<
  typeof KnowledgeExportCode
> = KnowledgeExportCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace KnowledgeExportCode$ {
  /** @deprecated use `KnowledgeExportCode$inboundSchema` instead. */
  export const inboundSchema = KnowledgeExportCode$inboundSchema;
  /** @deprecated use `KnowledgeExportCode$outboundSchema` instead. */
  export const outboundSchema = KnowledgeExportCode$outboundSchema;
}

/** @internal */
export const KnowledgeExportLanguage$inboundSchema: z.ZodType<
  KnowledgeExportLanguage,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: KnowledgeExportCode$inboundSchema,
});

/** @internal */
export type KnowledgeExportLanguage$Outbound = {
  code: string;
};

/** @internal */
export const KnowledgeExportLanguage$outboundSchema: z.ZodType<
  KnowledgeExportLanguage$Outbound,
  z.ZodTypeDef,
  KnowledgeExportLanguage
> = z.object({
  code: KnowledgeExportCode$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace KnowledgeExportLanguage$ {
  /** @deprecated use `KnowledgeExportLanguage$inboundSchema` instead. */
  export const inboundSchema = KnowledgeExportLanguage$inboundSchema;
  /** @deprecated use `KnowledgeExportLanguage$outboundSchema` instead. */
  export const outboundSchema = KnowledgeExportLanguage$outboundSchema;
  /** @deprecated use `KnowledgeExportLanguage$Outbound` instead. */
  export type Outbound = KnowledgeExportLanguage$Outbound;
}

export function knowledgeExportLanguageToJSON(
  knowledgeExportLanguage: KnowledgeExportLanguage,
): string {
  return JSON.stringify(
    KnowledgeExportLanguage$outboundSchema.parse(knowledgeExportLanguage),
  );
}

export function knowledgeExportLanguageFromJSON(
  jsonString: string,
): SafeParseResult<KnowledgeExportLanguage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KnowledgeExportLanguage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KnowledgeExportLanguage' from JSON`,
  );
}

/** @internal */
export const ResourceType$inboundSchema: z.ZodNativeEnum<typeof ResourceType> =
  z.nativeEnum(ResourceType);

/** @internal */
export const ResourceType$outboundSchema: z.ZodNativeEnum<typeof ResourceType> =
  ResourceType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResourceType$ {
  /** @deprecated use `ResourceType$inboundSchema` instead. */
  export const inboundSchema = ResourceType$inboundSchema;
  /** @deprecated use `ResourceType$outboundSchema` instead. */
  export const outboundSchema = ResourceType$outboundSchema;
}

/** @internal */
export const DestinationType$inboundSchema: z.ZodNativeEnum<
  typeof DestinationType
> = z.nativeEnum(DestinationType);

/** @internal */
export const DestinationType$outboundSchema: z.ZodNativeEnum<
  typeof DestinationType
> = DestinationType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DestinationType$ {
  /** @deprecated use `DestinationType$inboundSchema` instead. */
  export const inboundSchema = DestinationType$inboundSchema;
  /** @deprecated use `DestinationType$outboundSchema` instead. */
  export const outboundSchema = DestinationType$outboundSchema;
}

/** @internal */
export const DataDestination$inboundSchema: z.ZodType<
  DataDestination,
  z.ZodTypeDef,
  unknown
> = z.object({
  destinationType: DestinationType$inboundSchema,
  path: z.string(),
  sftpDetails: SftpConfig$inboundSchema.optional(),
  s3Details: S3Config$inboundSchema.optional(),
});

/** @internal */
export type DataDestination$Outbound = {
  destinationType: string;
  path: string;
  sftpDetails?: SftpConfig$Outbound | undefined;
  s3Details?: S3Config$Outbound | undefined;
};

/** @internal */
export const DataDestination$outboundSchema: z.ZodType<
  DataDestination$Outbound,
  z.ZodTypeDef,
  DataDestination
> = z.object({
  destinationType: DestinationType$outboundSchema,
  path: z.string(),
  sftpDetails: SftpConfig$outboundSchema.optional(),
  s3Details: S3Config$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DataDestination$ {
  /** @deprecated use `DataDestination$inboundSchema` instead. */
  export const inboundSchema = DataDestination$inboundSchema;
  /** @deprecated use `DataDestination$outboundSchema` instead. */
  export const outboundSchema = DataDestination$outboundSchema;
  /** @deprecated use `DataDestination$Outbound` instead. */
  export type Outbound = DataDestination$Outbound;
}

export function dataDestinationToJSON(
  dataDestination: DataDestination,
): string {
  return JSON.stringify(DataDestination$outboundSchema.parse(dataDestination));
}

export function dataDestinationFromJSON(
  jsonString: string,
): SafeParseResult<DataDestination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DataDestination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DataDestination' from JSON`,
  );
}

/** @internal */
export const KnowledgeExport$inboundSchema: z.ZodType<
  KnowledgeExport,
  z.ZodTypeDef,
  unknown
> = z.object({
  articleCategories: ArticleCategories$inboundSchema.default("searchable"),
  portalID: z.string(),
  language: z.lazy(() => KnowledgeExportLanguage$inboundSchema),
  exportUnpublishedOnly: z.boolean().default(false),
  resourceTypes: z.array(ResourceType$inboundSchema),
  dataDestination: z.lazy(() => DataDestination$inboundSchema),
});

/** @internal */
export type KnowledgeExport$Outbound = {
  articleCategories: string;
  portalID: string;
  language: KnowledgeExportLanguage$Outbound;
  exportUnpublishedOnly: boolean;
  resourceTypes: Array<string>;
  dataDestination: DataDestination$Outbound;
};

/** @internal */
export const KnowledgeExport$outboundSchema: z.ZodType<
  KnowledgeExport$Outbound,
  z.ZodTypeDef,
  KnowledgeExport
> = z.object({
  articleCategories: ArticleCategories$outboundSchema.default("searchable"),
  portalID: z.string(),
  language: z.lazy(() => KnowledgeExportLanguage$outboundSchema),
  exportUnpublishedOnly: z.boolean().default(false),
  resourceTypes: z.array(ResourceType$outboundSchema),
  dataDestination: z.lazy(() => DataDestination$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace KnowledgeExport$ {
  /** @deprecated use `KnowledgeExport$inboundSchema` instead. */
  export const inboundSchema = KnowledgeExport$inboundSchema;
  /** @deprecated use `KnowledgeExport$outboundSchema` instead. */
  export const outboundSchema = KnowledgeExport$outboundSchema;
  /** @deprecated use `KnowledgeExport$Outbound` instead. */
  export type Outbound = KnowledgeExport$Outbound;
}

export function knowledgeExportToJSON(
  knowledgeExport: KnowledgeExport,
): string {
  return JSON.stringify(KnowledgeExport$outboundSchema.parse(knowledgeExport));
}

export function knowledgeExportFromJSON(
  jsonString: string,
): SafeParseResult<KnowledgeExport, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KnowledgeExport$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KnowledgeExport' from JSON`,
  );
}
