/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const LanguageQueryParameter = {
  EnUS: "en-US",
  FRFR: "fr-FR",
  EnGB: "en-GB",
  ESES: "es-ES",
  ITIT: "it-IT",
  NLNL: "nl-NL",
  DADA: "da-DA",
  SvSE: "sv-SE",
  PTPT: "pt-PT",
  FIFI: "fi-FI",
  NoNB: "no-NB",
  NoNN: "no-NN",
  JAJA: "ja-JA",
  DEDE: "de-DE",
  PtBR: "pt-BR",
  ZhCN: "zh-CN",
  ZhTW: "zh-TW",
  KOKO: "ko-KO",
  RURU: "ru-RU",
  ELEL: "el-EL",
  TRTR: "tr-TR",
  PLPL: "pl-PL",
  CSCS: "cs-CS",
  SKSK: "sk-SK",
  HUHU: "hu-HU",
  SRSR: "sr-SR",
  ArSA: "ar-SA",
  HRHR: "hr-HR",
  RORO: "ro-RO",
  THTH: "th-TH",
  DeAT: "de-AT",
  ViVN: "vi-VN",
  IDID: "id-ID",
  MsMY: "ms-MY",
  FilPH: "fil-PH",
  FrCA: "fr-CA",
  HiIN: "hi-IN",
  UkUA: "uk-UA",
  BGBG: "bg-BG",
  SlSI: "sl-SI",
  SrRS: "sr-RS",
  XXXX: "xx-XX",
} as const;
export type LanguageQueryParameter = ClosedEnum<typeof LanguageQueryParameter>;

/** @internal */
export const LanguageQueryParameter$inboundSchema: z.ZodNativeEnum<
  typeof LanguageQueryParameter
> = z.nativeEnum(LanguageQueryParameter);

/** @internal */
export const LanguageQueryParameter$outboundSchema: z.ZodNativeEnum<
  typeof LanguageQueryParameter
> = LanguageQueryParameter$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LanguageQueryParameter$ {
  /** @deprecated use `LanguageQueryParameter$inboundSchema` instead. */
  export const inboundSchema = LanguageQueryParameter$inboundSchema;
  /** @deprecated use `LanguageQueryParameter$outboundSchema` instead. */
  export const outboundSchema = LanguageQueryParameter$outboundSchema;
}
