/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CreatedBy,
  CreatedBy$inboundSchema,
  CreatedBy$Outbound,
  CreatedBy$outboundSchema,
} from "./createdby.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Specifies which console the prompt applies to: 'knowledge', 'advisor', or 'custom' (for prompts used outside any console).
 */
export const UseFor = {
  Knowledge: "knowledge",
  Advisor: "advisor",
  Custom: "custom",
} as const;
/**
 * Specifies which console the prompt applies to: 'knowledge', 'advisor', or 'custom' (for prompts used outside any console).
 */
export type UseFor = ClosedEnum<typeof UseFor>;

/**
 * The 'channel' for this prompt. If the `useFor` is set to 'knowledge' then article is used. If `useFor` is set to 'advisor', then either 'chat' or 'email' can be used.
 */
export const AppliesTo = {
  Article: "article",
  Chat: "chat",
  Email: "email",
} as const;
/**
 * The 'channel' for this prompt. If the `useFor` is set to 'knowledge' then article is used. If `useFor` is set to 'advisor', then either 'chat' or 'email' can be used.
 */
export type AppliesTo = ClosedEnum<typeof AppliesTo>;

/**
 * The output format for the generated output.
 */
export const OutputFormat = {
  Html: "html",
  Text: "text",
} as const;
/**
 * The output format for the generated output.
 */
export type OutputFormat = ClosedEnum<typeof OutputFormat>;

/**
 * Review status of the prompt.
 */
export const ReviewStatus = {
  Published: "published",
} as const;
/**
 * Review status of the prompt.
 */
export type ReviewStatus = ClosedEnum<typeof ReviewStatus>;

export const DisplayAt = {
  ArticleContentArea: "article.content-area",
  ArticleMetadata: "article.metadata",
} as const;
export type DisplayAt = ClosedEnum<typeof DisplayAt>;

export type PromptTemplate = {
  /**
   * Name of the prompt template
   */
  name: string;
  /**
   * ID of the prompt template from the AI console
   */
  id: string;
  description: string;
  /**
   * A boolean showing whether a prompt is active or inactive.
   */
  active: boolean;
  /**
   * Specifies which console the prompt applies to: 'knowledge', 'advisor', or 'custom' (for prompts used outside any console).
   */
  useFor: UseFor;
  /**
   * The 'channel' for this prompt. If the `useFor` is set to 'knowledge' then article is used. If `useFor` is set to 'advisor', then either 'chat' or 'email' can be used.
   */
  appliesTo: AppliesTo;
  /**
   * The prompt instructions.
   */
  instruction: string;
  /**
   * The output format for the generated output.
   */
  outputFormat: OutputFormat;
  /**
   * Date and time when the prompt template was created.
   */
  createdOn: Date;
  /**
   * Date and time when the prompt was last updated.
   */
  modifiedDate: Date;
  createdBy: CreatedBy;
  /**
   * Review status of the prompt.
   */
  reviewStatus: ReviewStatus;
  /**
   * A boolean showing whether the prompt template came out of the box or is a custom prompt.
   */
  isSystemCreated: boolean;
  /**
   * This will return the specified field to update once a user inserts the generated content. This value can be one of the following:
   *
   * @remarks
   *
   * - title
   * - content
   * - keyword
   * - description
   * - summary
   * - replyarea
   * - notes
   * - subject
   * - classification
   *
   * It can also return a custom attribute which will follow the following convention:
   *
   * `custom.<attributeType>.<customAttributeName>`
   */
  fieldToUpdate: string;
  displayAt?: Array<DisplayAt> | undefined;
};

/** @internal */
export const UseFor$inboundSchema: z.ZodNativeEnum<typeof UseFor> = z
  .nativeEnum(UseFor);

/** @internal */
export const UseFor$outboundSchema: z.ZodNativeEnum<typeof UseFor> =
  UseFor$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UseFor$ {
  /** @deprecated use `UseFor$inboundSchema` instead. */
  export const inboundSchema = UseFor$inboundSchema;
  /** @deprecated use `UseFor$outboundSchema` instead. */
  export const outboundSchema = UseFor$outboundSchema;
}

/** @internal */
export const AppliesTo$inboundSchema: z.ZodNativeEnum<typeof AppliesTo> = z
  .nativeEnum(AppliesTo);

/** @internal */
export const AppliesTo$outboundSchema: z.ZodNativeEnum<typeof AppliesTo> =
  AppliesTo$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppliesTo$ {
  /** @deprecated use `AppliesTo$inboundSchema` instead. */
  export const inboundSchema = AppliesTo$inboundSchema;
  /** @deprecated use `AppliesTo$outboundSchema` instead. */
  export const outboundSchema = AppliesTo$outboundSchema;
}

/** @internal */
export const OutputFormat$inboundSchema: z.ZodNativeEnum<typeof OutputFormat> =
  z.nativeEnum(OutputFormat);

/** @internal */
export const OutputFormat$outboundSchema: z.ZodNativeEnum<typeof OutputFormat> =
  OutputFormat$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OutputFormat$ {
  /** @deprecated use `OutputFormat$inboundSchema` instead. */
  export const inboundSchema = OutputFormat$inboundSchema;
  /** @deprecated use `OutputFormat$outboundSchema` instead. */
  export const outboundSchema = OutputFormat$outboundSchema;
}

/** @internal */
export const ReviewStatus$inboundSchema: z.ZodNativeEnum<typeof ReviewStatus> =
  z.nativeEnum(ReviewStatus);

/** @internal */
export const ReviewStatus$outboundSchema: z.ZodNativeEnum<typeof ReviewStatus> =
  ReviewStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReviewStatus$ {
  /** @deprecated use `ReviewStatus$inboundSchema` instead. */
  export const inboundSchema = ReviewStatus$inboundSchema;
  /** @deprecated use `ReviewStatus$outboundSchema` instead. */
  export const outboundSchema = ReviewStatus$outboundSchema;
}

/** @internal */
export const DisplayAt$inboundSchema: z.ZodNativeEnum<typeof DisplayAt> = z
  .nativeEnum(DisplayAt);

/** @internal */
export const DisplayAt$outboundSchema: z.ZodNativeEnum<typeof DisplayAt> =
  DisplayAt$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DisplayAt$ {
  /** @deprecated use `DisplayAt$inboundSchema` instead. */
  export const inboundSchema = DisplayAt$inboundSchema;
  /** @deprecated use `DisplayAt$outboundSchema` instead. */
  export const outboundSchema = DisplayAt$outboundSchema;
}

/** @internal */
export const PromptTemplate$inboundSchema: z.ZodType<
  PromptTemplate,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  id: z.string(),
  description: z.string(),
  active: z.boolean(),
  useFor: UseFor$inboundSchema,
  appliesTo: AppliesTo$inboundSchema,
  instruction: z.string(),
  outputFormat: OutputFormat$inboundSchema,
  createdOn: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  modifiedDate: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ),
  createdBy: CreatedBy$inboundSchema,
  reviewStatus: ReviewStatus$inboundSchema,
  isSystemCreated: z.boolean(),
  fieldToUpdate: z.string(),
  displayAt: z.array(DisplayAt$inboundSchema).optional(),
});

/** @internal */
export type PromptTemplate$Outbound = {
  name: string;
  id: string;
  description: string;
  active: boolean;
  useFor: string;
  appliesTo: string;
  instruction: string;
  outputFormat: string;
  createdOn: string;
  modifiedDate: string;
  createdBy: CreatedBy$Outbound;
  reviewStatus: string;
  isSystemCreated: boolean;
  fieldToUpdate: string;
  displayAt?: Array<string> | undefined;
};

/** @internal */
export const PromptTemplate$outboundSchema: z.ZodType<
  PromptTemplate$Outbound,
  z.ZodTypeDef,
  PromptTemplate
> = z.object({
  name: z.string(),
  id: z.string(),
  description: z.string(),
  active: z.boolean(),
  useFor: UseFor$outboundSchema,
  appliesTo: AppliesTo$outboundSchema,
  instruction: z.string(),
  outputFormat: OutputFormat$outboundSchema,
  createdOn: z.date().transform(v => v.toISOString()),
  modifiedDate: z.date().transform(v => v.toISOString()),
  createdBy: CreatedBy$outboundSchema,
  reviewStatus: ReviewStatus$outboundSchema,
  isSystemCreated: z.boolean(),
  fieldToUpdate: z.string(),
  displayAt: z.array(DisplayAt$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PromptTemplate$ {
  /** @deprecated use `PromptTemplate$inboundSchema` instead. */
  export const inboundSchema = PromptTemplate$inboundSchema;
  /** @deprecated use `PromptTemplate$outboundSchema` instead. */
  export const outboundSchema = PromptTemplate$outboundSchema;
  /** @deprecated use `PromptTemplate$Outbound` instead. */
  export type Outbound = PromptTemplate$Outbound;
}

export function promptTemplateToJSON(promptTemplate: PromptTemplate): string {
  return JSON.stringify(PromptTemplate$outboundSchema.parse(promptTemplate));
}

export function promptTemplateFromJSON(
  jsonString: string,
): SafeParseResult<PromptTemplate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PromptTemplate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PromptTemplate' from JSON`,
  );
}
