/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type QuickpickRating = {
  /**
   * The numerical ID of the Casebase Release.
   */
  id: string;
  /**
   * name of the case or article
   */
  name: string;
  /**
   * The ID of the guided help profile.<br>
   *
   * @remarks
   * 1 will always be the **system profile**.
   */
  profileId: string;
};

/** @internal */
export const QuickpickRating$inboundSchema: z.ZodType<
  QuickpickRating,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  profileId: z.string(),
});

/** @internal */
export type QuickpickRating$Outbound = {
  id: string;
  name: string;
  profileId: string;
};

/** @internal */
export const QuickpickRating$outboundSchema: z.ZodType<
  QuickpickRating$Outbound,
  z.ZodTypeDef,
  QuickpickRating
> = z.object({
  id: z.string(),
  name: z.string(),
  profileId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QuickpickRating$ {
  /** @deprecated use `QuickpickRating$inboundSchema` instead. */
  export const inboundSchema = QuickpickRating$inboundSchema;
  /** @deprecated use `QuickpickRating$outboundSchema` instead. */
  export const outboundSchema = QuickpickRating$outboundSchema;
  /** @deprecated use `QuickpickRating$Outbound` instead. */
  export type Outbound = QuickpickRating$Outbound;
}

export function quickpickRatingToJSON(
  quickpickRating: QuickpickRating,
): string {
  return JSON.stringify(QuickpickRating$outboundSchema.parse(quickpickRating));
}

export function quickpickRatingFromJSON(
  jsonString: string,
): SafeParseResult<QuickpickRating, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QuickpickRating$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QuickpickRating' from JSON`,
  );
}
