/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  SearchReplacement,
  SearchReplacement$inboundSchema,
  SearchReplacement$Outbound,
  SearchReplacement$outboundSchema,
} from "./searchreplacement.js";
import {
  StaticReplacement,
  StaticReplacement$inboundSchema,
  StaticReplacement$Outbound,
  StaticReplacement$outboundSchema,
} from "./staticreplacement.js";

export type Replacement = SearchReplacement | StaticReplacement;

/** @internal */
export const Replacement$inboundSchema: z.ZodType<
  Replacement,
  z.ZodTypeDef,
  unknown
> = z.union([SearchReplacement$inboundSchema, StaticReplacement$inboundSchema]);

/** @internal */
export type Replacement$Outbound =
  | SearchReplacement$Outbound
  | StaticReplacement$Outbound;

/** @internal */
export const Replacement$outboundSchema: z.ZodType<
  Replacement$Outbound,
  z.ZodTypeDef,
  Replacement
> = z.union([
  SearchReplacement$outboundSchema,
  StaticReplacement$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Replacement$ {
  /** @deprecated use `Replacement$inboundSchema` instead. */
  export const inboundSchema = Replacement$inboundSchema;
  /** @deprecated use `Replacement$outboundSchema` instead. */
  export const outboundSchema = Replacement$outboundSchema;
  /** @deprecated use `Replacement$Outbound` instead. */
  export type Outbound = Replacement$Outbound;
}

export function replacementToJSON(replacement: Replacement): string {
  return JSON.stringify(Replacement$outboundSchema.parse(replacement));
}

export function replacementFromJSON(
  jsonString: string,
): SafeParseResult<Replacement, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Replacement$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Replacement' from JSON`,
  );
}
