/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type SchemasWSErrorCommonDetail = {
  key: string;
  value?: string | undefined;
};

/** @internal */
export const SchemasWSErrorCommonDetail$inboundSchema: z.ZodType<
  SchemasWSErrorCommonDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string(),
  value: z.string().optional(),
});

/** @internal */
export type SchemasWSErrorCommonDetail$Outbound = {
  key: string;
  value?: string | undefined;
};

/** @internal */
export const SchemasWSErrorCommonDetail$outboundSchema: z.ZodType<
  SchemasWSErrorCommonDetail$Outbound,
  z.ZodTypeDef,
  SchemasWSErrorCommonDetail
> = z.object({
  key: z.string(),
  value: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SchemasWSErrorCommonDetail$ {
  /** @deprecated use `SchemasWSErrorCommonDetail$inboundSchema` instead. */
  export const inboundSchema = SchemasWSErrorCommonDetail$inboundSchema;
  /** @deprecated use `SchemasWSErrorCommonDetail$outboundSchema` instead. */
  export const outboundSchema = SchemasWSErrorCommonDetail$outboundSchema;
  /** @deprecated use `SchemasWSErrorCommonDetail$Outbound` instead. */
  export type Outbound = SchemasWSErrorCommonDetail$Outbound;
}

export function schemasWSErrorCommonDetailToJSON(
  schemasWSErrorCommonDetail: SchemasWSErrorCommonDetail,
): string {
  return JSON.stringify(
    SchemasWSErrorCommonDetail$outboundSchema.parse(schemasWSErrorCommonDetail),
  );
}

export function schemasWSErrorCommonDetailFromJSON(
  jsonString: string,
): SafeParseResult<SchemasWSErrorCommonDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SchemasWSErrorCommonDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchemasWSErrorCommonDetail' from JSON`,
  );
}
