/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Identifies this replacement as a **search result**. At execution, results from a portal search will replace the variable `name` in the prompt template.
 */
export const SearchReplacementType = {
  Search: "search",
} as const;
/**
 * Identifies this replacement as a **search result**. At execution, results from a portal search will replace the variable `name` in the prompt template.
 */
export type SearchReplacementType = ClosedEnum<typeof SearchReplacementType>;

export type SearchReplacement = {
  /**
   * Identifies this replacement as a **search result**. At execution, results from a portal search will replace the variable `name` in the prompt template.
   */
  type: SearchReplacementType;
  /**
   * The placeholder variable in the prompt template that will be replaced with search results.
   */
  name: string;
  /**
   * The portal identifier where the search will be performed.
   */
  portalId: string;
  /**
   * The search query string to run against the specified portal.
   */
  q: string;
};

/** @internal */
export const SearchReplacementType$inboundSchema: z.ZodNativeEnum<
  typeof SearchReplacementType
> = z.nativeEnum(SearchReplacementType);

/** @internal */
export const SearchReplacementType$outboundSchema: z.ZodNativeEnum<
  typeof SearchReplacementType
> = SearchReplacementType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SearchReplacementType$ {
  /** @deprecated use `SearchReplacementType$inboundSchema` instead. */
  export const inboundSchema = SearchReplacementType$inboundSchema;
  /** @deprecated use `SearchReplacementType$outboundSchema` instead. */
  export const outboundSchema = SearchReplacementType$outboundSchema;
}

/** @internal */
export const SearchReplacement$inboundSchema: z.ZodType<
  SearchReplacement,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: SearchReplacementType$inboundSchema,
  name: z.string(),
  portalId: z.string(),
  q: z.string(),
});

/** @internal */
export type SearchReplacement$Outbound = {
  type: string;
  name: string;
  portalId: string;
  q: string;
};

/** @internal */
export const SearchReplacement$outboundSchema: z.ZodType<
  SearchReplacement$Outbound,
  z.ZodTypeDef,
  SearchReplacement
> = z.object({
  type: SearchReplacementType$outboundSchema,
  name: z.string(),
  portalId: z.string(),
  q: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SearchReplacement$ {
  /** @deprecated use `SearchReplacement$inboundSchema` instead. */
  export const inboundSchema = SearchReplacement$inboundSchema;
  /** @deprecated use `SearchReplacement$outboundSchema` instead. */
  export const outboundSchema = SearchReplacement$outboundSchema;
  /** @deprecated use `SearchReplacement$Outbound` instead. */
  export type Outbound = SearchReplacement$Outbound;
}

export function searchReplacementToJSON(
  searchReplacement: SearchReplacement,
): string {
  return JSON.stringify(
    SearchReplacement$outboundSchema.parse(searchReplacement),
  );
}

export function searchReplacementFromJSON(
  jsonString: string,
): SafeParseResult<SearchReplacement, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchReplacement$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchReplacement' from JSON`,
  );
}
